### ISSUE TITLE
Logo/Icon Proposals

### ISSUE THREAD

**Issue by jbeguna04** [imba/imba#114]
Hi good day! I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by rmdwirizki** [comment]
@somebee I think you really should consider this proposal

**Comment by iamtirado** [comment]
As a full-time brand designer and part-time Imba user, I couldn't help but experiment making a new logo for Imba.
Here's one concept I have made.
![image](https://user-images.githubusercontent.com/13579055/48782350-de137e80-ec92-11e8-8a8e-d16d221af87f.png)
@somebee

**Comment by iamtirado** [comment]
Here's another concept @somebee 
![image](https://user-images.githubusercontent.com/13579055/48788517-d9a19280-ec9f-11e8-9dbb-7db0d2d55261.png)
Wings have been a symbol of speed from ancient times.

**Comment by iamtirado** [comment]
Here's another concept @somebee
This one uses wings that are an ancient symbol of speed.
![imba02-logo](https://user-images.githubusercontent.com/13579055/48792252-a57e9f80-eca8-11e8-98d3-b37bc28d1c4c.jpg)
![imba02-website](https://user-images.githubusercontent.com/13579055/48792253-a57e9f80-eca8-11e8-9554-40b276eaba93.jpg)

**Comment by somebee** [comment]
Very nice :) I like the first one best. I'd love it if you experimented with the existing concept as well - a beefed up (overpowered) guy made of angle brackets somehow appeals to me :P

**Comment by koolamusic** [comment]
The colors in the second revision feel like I am reading a DC Flash Comic, which I think is a good representation for speed, the first concept resonates better in both icon and aesthetic, 
- I suggest utilizing a similar color scheme like the second design 
- Experimenting with angle brackets (rounded variations can be considered)
- Take to mind the use cases for the icon too (IDEs, website, docs, favicons, splash screens etc)

**Comment by scanf** [comment]
Closing this as it has been open for a while and the discussion has moved in other issues. 
See #245
