### ISSUE TITLE
How to print HTML Entities in render 

### ISSUE THREAD

**Issue by rmdwirizki** [imba/imba#116]
How to print HTML Entities in Imba? putting it in string is clearly not possible. 

This code just print  a plain string.

```html
<span> "&amp;"
```

This code produce error.

```html
<span> &amp;
```

**Comment by lucianoratamero** [comment]
what I've been doing is to set the html property directly:

`<span html="&amp;">`

it renders:

`<span>&amp;</span>`

**Comment by rmdwirizki** [comment]
neat!
