### ISSUE TITLE
The best way possible to make a standard loop (pagination)

### ISSUE THREAD

**Issue by rmdwirizki** [imba/imba#117]
How to iterate through a standard js way of looping. This is what I want to achieve in render method:

```javascript
for(let num = 1; num < pageLength; num++)
  <li.page-item .active=(num == pageIndex)>
    <a.page-link href="" :tap.setPage(num)> 
      num
```

There is no hint in the [docs](http://imba.io/guides/language/loops) to achieve that. So instead I have to create an array of number and looping through that array. This is my current code.

```imba
for num in pagenums
  <li.page-item .active=(num == pageIndex)>
    <a.page-link href="" :tap.setPage(num)> 
      num
```

Where `pagenums` is:

```imba
def pagenums
    return Array(@pageLength).fill().map do |v,i| return i + 1
```
The method return an array according to the `pageLength` property.

```javascript
[1,2,3,4,5,6,7,8,9,10]
```

**Comment by alexandre-mouton-brady** [comment]
Hey there!

I was actually wondering the same thing and then realized that since Imba is strongly inspired by CoffeeScript (for the syntax part at least), I might try my luck with their syntax and it turns out it is actually the same. Here's how you'd do it I think:

```
tag App < main
	prop page default: ['hello', 'world', 'from', 'imba']
	prop pageIndex default: 1

	def setPage num
		pageIndex = num

	def render
		let pageLength = page:length + 1

		<self> for num in [1..pageLength]
			<li.page-item .active=(num == pageIndex)>
				<a.page-link href="" :tap.prevent.setPage(num)>
					num

Imba.mount <App>
```
