### ISSUE TITLE
Custom naming for div tags

### ISSUE THREAD

**Issue by altteo** [imba/imba#122]
For clear css and more component-like approach, could you please add the following 3 lines of code in the **findTagType** function in the **Imba.Tags** class (somewhere near 948 line in tag.imba):
```
unless klass
......
  else
     klass = self['div']
     klass.@classes.push type 
```

This let us use any word in naming tags, like `<seduction>`, the div will be created with the css class "seduction", that would make html much more readable and css much more close-scoped.

**Comment by altteo** [comment]
The code above is wrong, Here is working one:
```
def findTagType type
		let klass = self[type] || self["custom:{type}"]
		unless klass
			if type.substr(0,4) == 'svg:'
				klass = defineTag(type,'svg:element')

			elif Imba.HTML_TAGS.indexOf(type) >= 0
				klass = defineTag(type,'element')

				if let attrs = Imba.HTML_ATTRS[type]
					for name in attrs.split(" ")
						Imba.attr(klass,name)

				if let props = Imba.HTML_PROPS[type]
					for name in props.split(" ")
						Imba.attr(klass,name,dom: yes)
			# to let custom html-tags
			else
				let custom = "custom:{type}"
				Imba.HTML_TAGS.push custom
				Imba.HTML_ATTRS[custom] = Imba.HTML_ATTRS['div']
				Imba.HTML_PROPS[custom] = Imba.HTML_PROPS['div']

				klass = defineTag(custom,'element')

				if let attrs = Imba.HTML_ATTRS[custom]
					for name in attrs.split(" ")
						Imba.attr(klass,name)

				if let props = Imba.HTML_PROPS[custom]
					for name in props.split(" ")
						Imba.attr(klass,name,dom: yes)

				klass.@classes.push type

		return klass
```

and also in defineTag we should add two lines
```
if  nsidx >= 0
			ns = fullName.substr(0,nsidx)
			name = fullName.substr(nsidx + 1)
			if ns == 'svg' and !supr
				supr = 'svg:element'
			if ns == 'custom' # <- this ones
				name = 'div'
```

And of course if you could do it better, I'll be happy!

**Comment by somebee** [comment]
Hey @altteo! Do you want to declare `tag seduction` with custom logic, or just have a a shorthand for creating `<div.seduction>`? If the latter, you can just write `<.seduction>`. I just had a kid, but I'm slowly coming back to Imba now :)

**Comment by altteo** [comment]
@somebee My congratulations! How do name him/her/it? 🥇 
Thanks for `<.seduction>` - this what I wanted to achive. 
Another short question why svg tags have prefix '_' in classes?
I gathered a lot of questions and ideas, so waiting for you very much.

**Comment by altteo** [comment]
I really need to implement this. I see it as some Imba settings that influence the behavior. At the moment for me two things matters: css class prefixes (specially for svg) and generating div (with class = tag) for unknown tags.
