### ISSUE TITLE
Colocated styling / styled tags

### ISSUE THREAD

**Issue by ghengeveld** [imba/imba#130]
Is there a way to tie styles directly to a tag/component, without the use of (hand written) CSS classes? I'm a huge fan of [styled components](https://www.styled-components.com/) and would really like to have something similar, e.g. "styled-tags".

Linking styles directly to a tag is far superior to using class names and writing CSS files, because it eliminates unused CSS rules, avoids bugs caused by typos in class names and prevents unwanted cascading. It also encourages separating layout (styled) components from logic components.

**Comment by judofyr** [comment]
Yeah, I have some experiments in that repo (including an `inheritance` branch which did things a bit differently), but I haven't looked at it in a while. When I wrote it, `styled-components` wasn't as developed/used as it is today, so it might be a good idea to look more at it for inspiration (and for familiarity for other developers).

**Comment by scanf** [comment]
You can use the comment blocks 😄  It was added in 1.5.x. Here is an Imba Changelog episode https://scrimba.com/c/c7P26Ehg
