### ISSUE TITLE
Imba Documentation

### ISSUE THREAD

**Issue by koolamusic** [imba/imba#134]
So The Repository has no documentation for 
- Contributing
- Code of Conduct
- Issue Templates and Pull Request Templates

This can be vague, but at least there are great starting points which can work for Imba, I wouldn't mind sending a PR for this

**Comment by somebee** [comment]
I'd love a pull request with a starting point :) We welcome all help we can get!

**Comment by scanf** [comment]
@koolamusic thanks for taking this on. If you have time it would also be awesome to add this http://makeapullrequest.com/

Hoping it will encourage more people to contribute :smile:
