### ISSUE TITLE
Support for special arguments in event handlers

### ISSUE THREAD

**Issue by somebee** [imba/imba#144]
The syntax for binding event handlers inline is heavily inspired by Vue. One thing I am still missing in Imba is the ability to explicitly pass in the event in the handler. I propose to allow this using special variable `$event`, and possibly allow for a few more special variables like this inside handlers.

```imba
# Still default to calling context.someFunction(tapEvent)
<div :tap.someFunction>

# Explicit parens should call without args context.someFunction()
<div :tap.someFunction()>

# The special $event is a placeholder - replaced with real event on call
<div :tap.someFunction(someData,$event)>
```

**Comment by somebee** [comment]
Implemented both suggestions in master now.

* Including empty parens will make sure the handler is called without any arguments
* `$event` will be replaced with the actual event, while any other `$identifier` will be replaced with the result of node[identifier](). If node[identifier] is not a function it will give a warning. 

This is actually pretty useful for stuff like `<self>  <input :change.updateTitle($value)>`

**Comment by altteo** [comment]
Good idea at the moment i do like this:
```
<div :tap=(do |event| someFunc('hello', event))>
```

**Comment by somebee** [comment]
Now you could do `<div :tap.someFunc('hello',$event)>` :) Given that someFunc is a method on the outer tag (<self>)

**Comment by somebee** [comment]
Btw, this isn't documented yet, but if you want to be able to automatically delegate these functions to some sort of backing controller / store, the event handler in Imba calls context.getHandler('someFunc',event), and if you return another object from there, someFunc will be called on that object instead.

**Comment by altteo** [comment]
This need example to understand. But I prefer to directly call controller functions from the interface (validation etc.).
And why node[identifier]? It is browser events.. or I'm missing something?

**Comment by allain** [comment]
If you're doing magic replacement from the node fields ($value, etc), you could have it go through props on the event first. Allowing the imba.io example to be written as:

```imba
var state = {x: 0, y: 0}

tag App
	def onClick x, y
		state:x = x
		state:y = y

	def render
		<self>
			<div :tap.onClick($x, $y)> "Mouse clicked at {state:x or 0} {state:y or 0}"

Imba.mount <App>
```

Or with destructuring for its params it could be this too:
```imba
var state = {x: 0, y: 0}

tag App
	def onClick {x, y}
		state:x = x
		state:y = y

	def render
		<self>
			<div :tap.onClick($event)> "Mouse clicked at {state:x or 0} {state:y or 0}"

Imba.mount <App>
```

**Comment by somebee** [comment]
That might be good, but I guess you more often want to access something from the element than from the event? I don't think:
```imba
var state = {x: 0, y: 0}

tag App
	def onClick e
		state:x = e.x
		state:y = e.y

	def render
		<self>
			<div :tap.onClick> "Mouse clicked at {state:x or 0} {state:y or 0}"

Imba.mount <App>
```
Is much worse than your example? Event has a data-attribute, but I would rather expect `$data` to refer to the data of the tag than data of event (which is usually empty).

**Comment by somebee** [comment]
> If you're doing magic replacement from the node fields ($value, etc), you could have it go through props on the event first. Allowing the imba.io example to be written as:
> 
> ```
> var state = {x: 0, y: 0}
> 
> tag App
> 	def onClick x, y
> 		state:x = x
> 		state:y = y
> 
> 	def render
> 		<self>
> 			<div :tap.onClick($x, $y)> "Mouse clicked at {state:x or 0} {state:y or 0}"
> 
> Imba.mount <App>
> ```
> 
> Or with destructuring for its params it could be this too:
> 
> ```
> var state = {x: 0, y: 0}
> 
> tag App
> 	def onClick {x, y}
> 		state:x = x
> 		state:y = y
> 
> 	def render
> 		<self>
> 			<div :tap.onClick($event)> "Mouse clicked at {state:x or 0} {state:y or 0}"
> 
> Imba.mount <App>
> ```

@allain: I've changed the behaviour to this now. I see that it makes a lot more sense :)

**Comment by allain** [comment]
Nice!
