### ISSUE TITLE
How to achieve two way binding in custom tag 

### ISSUE THREAD

**Issue by akki-jat** [imba/imba#146]
Take a example of Input tag.

This code is not reactive

```
import IInput from './input'

var state = { 
    input: 'test'
}

Imba.mount <IInput[state:input] type='text'>

// input tag
export tag IInput
    prop type

    def render
        <self>
            <input[data] type=@type>
```

I know if I pass whole object & operate on object property then it will be reactive. But I wanna know can I achieve something like two way binding with specific object property.

**Comment by foxbunny** [comment]
The way you have it set up, the `IInput` is receiving a string 'test' as `data`. So it cannot update the state object. It's like saying:

```imba
def foo x
    x = 'test'

foo state:input
```

You need to pass the whole state object and bind `<input[data:input]>`.

Alternatively, you can reshape the state like this:

```
var state = {
    input: {
        value: 'test'
    }
}
```

And bind `<input[data:value]>`.
