### ISSUE TITLE
navigator should be special global variable

### ISSUE THREAD

**Issue by taw** [imba/imba#155]
[For things like this](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/geolocation).

There's probably more browser globals like that.

From a quick grep, that's defined in that list in `export class RootScope < Scope` ?

(I guess `window:navigator` works as a workaround)

**Comment by somebee** [comment]
Yeah, I've been using window:navigator usually. Right now i think the only window property we include as a global is document. Adding more could be a slippery slope. See all [properties on window](https://developer.mozilla.org/en-US/docs/Web/API/Window).

**Comment by taw** [comment]
So from what I understand, imba 2 will not need this.
