### ISSUE TITLE
TypeError with specific tag classes

### ISSUE THREAD

**Issue by akaufmann** [imba/imba#157]
If  you have a tag class like (this is a valid HTML class e.g. available by [UIkit](https://getuikit.com/docs/width#responsive-width) ...
```html
<div.uk-width-expand@m>
```
...you get an error message that is not really helpful:
```js
TypeError: Cannot read property 'end' of undefined
    at Object.tag.render (/Users/akaufmann/devel/imba/hello-world-imba/src/pages/Home.imba:34:9)
    at Object.Imba.Tag.commit (/Users/akaufmann/devel/imba/hello-world-imba/node_modules/imba/lib/imba/dom/tag.js:615:42)
```

The line number (#34) is also incorrect. In most cases it is 15 - 5 lines above :)

**Comment by somebee** [comment]
Hmm, which version are you running? I don't think the above line would be the problem. It compiles and works perfectly here. Are you setting any additional properties on the div?

**Comment by akaufmann** [comment]
You're right but it has something to do with the `@` sign (if you remove one of the `@`'s it works). You also need a tag (e.g. `<video>`) with an unknown attribute (?) for Imba. I was able to track it down:

```html
# client.imba
tag App    
  def render
    <div.uk-width-1-2@m>

    <div.uk-width-1-2@m>
      <video autoplay>

Imba.mount <App>
``` 

Stack trace:
```bash
client.imba:26 Uncaught TypeError: Cannot read property 'end' of undefined
    at Object.tag.render (client.imba:26)
    at Object.Imba.Tag.commit (tag.imba:505)
    at Object.Imba.Tag.end (tag.imba:524)
    at eval (client.imba:32)
    at Object../src/client.imba (client.js:250)
    at __webpack_require__ (client.js:20)
    at client.js:84
    at client.js:87
```

**Comment by somebee** [comment]
A few issue here
1. Rendering inside a tag *must* be wrapped in `<self>`.
2. Two elements cannot use the same named reference (`@somename`)

```imba
tag App    
  def render
    <self>
      <div@m1.uk-width-1-2>
      <div@m2.uk-width-1-2>
        <video autoplay>

Imba.mount <App>
```

**Comment by akaufmann** [comment]
1) I removed the `<self>` because it made no difference for this issue.
2) Then how can you get something like the `@*` modifier from UIkit to work without Imba assuming a named reference?

But regardless of this, could a better error message be displayed in such cases? I haven't found any information about named references and `Cannot read property 'end' of undefined` doesn't help.

**Comment by somebee** [comment]
Didn't mean to sound blunt; I totally agree that the error message is extremely bad. I'm not too familiar with UIkit - what is the `@*` modifier. Couldn't find anything about it in the docs, but maybe I don't know where to look.

**Comment by akaufmann** [comment]
It affects DOM elements, e.g. for certain device widths (responsive width). For example, if the class `.uk-width-*@m` is specified, grid columns are stacked for sizes smaller than 960px. 

See https://getuikit.com/docs/width#responsive-width.

**Comment by somebee** [comment]
Oh, I actually thought `@` was not allowed in css classes. It certainly is not allowed in the regular Imba syntax. You could work around it using:
`<div.{"uk-width-1-2-@m"}>`

**Comment by akaufmann** [comment]
Ah, okay. Thanks @somebee for the help! I'm looking forward to Elm-like error messages in Imba ;-)
