### ISSUE TITLE
Extra await in the docs

### ISSUE THREAD

**Issue by MinimumViablePerson** [imba/imba#165]
http://imba.io/guides/essentials/state-management#state-management

```
def load
	var res = await window.fetch("/items")
	var data = await res.json
	MyState:items = data
	# just notify Imba that it should reschedule items
	Imba.commit
```

I'm pretty new to Imba, but in this snippet found on the page linked at the top, I don't see why we have to `await` for res.json the second time since it should no longer be wrapped in a promise. Perhaps I am missing something, but just wanted to point this out.

**Comment by allain** [comment]
because the fetch api define json() to return a promise: https://developer.mozilla.org/en-US/docs/Web/API/Body/json

If you don't use await, MyState:items = data would assign a promise rather than the JSON for he items.

**Comment by scanf** [comment]
Looks like this has been addressed, @MinimumViablePerson feel free to reword that section of the docs to make it more clear. Thanks.
