### ISSUE TITLE
Hydrate existing markup with Imba (...kind of SSR implementation)

### ISSUE THREAD

**Issue by iloginow** [imba/imba#184]
Hi. First of all I'd like to thank you guys for this repo. Imba is a great piece of work! I'm really excited about giving it a try. What I want to do with Imba is a kind of landig page prototype... Or maybe, if we take it even further, it could be a universal front-end solution for a bunch of php and python web frameworks. But in order to get there we need a possibility to hydrate an existing DOM structure, not just generate it from scratch with JavaScript. Unfortunately I didn't have enough time to study the Imba code base properly just yet. So I just wanted to ask if you guys have possibly thought of some similar solution?  Or maybe you could give me an idea... or some sort of starting point... so that I can start implementing this feature myself? What comes to my mind is some kind of "id system" that would bind existing DOM elements with their Imba counterparts, so that Imba could use those DOM elements in the same manner as if it'd just generated them itself.

Thank you again...
I'd appreciate any answer.

**Comment by athif23** [comment]
One question, what the use of this hydrate thing? I'm not really understand about this.
Thanks.

**Comment by tcrowe** [comment]
I also wondered if it can be used for server-side-rendering(SSR). It's okay if not. Could you give an example if it can be used for SSR though?

SSR hydration is like you send some initial state to the client so when it mounts it doesn't render something different.

**Comment by iloginow** [comment]
@athif23 https://ssr.vuejs.org https://flaviocopes.com/react-server-side-rendering/

**Comment by athif23** [comment]
@iloginow Yeah, thanks for the info. I just read them. I think this will be hard to implements. But, I hope we have this soon enough.

**Comment by lassemt** [comment]
Would love to rehydrate pages created with a Imba static page generator⚡️
