### ISSUE TITLE
issue when checking CSS grid 'grid-template' attribute 

### ISSUE THREAD

**Issue by bofeiw** [imba/imba#196]
<img width="1010" alt="Screen Shot 2019-04-29 at 2 52 29 am" src="https://user-images.githubusercontent.com/34177142/56867602-47f63800-6a2a-11e9-84ab-a4ce514572e0.png">

In line 5 - 7, there are some red error underlines that indicate something went wrong. But this css is validated under css W3C validator, and the error underline should not appear. Please check it out.

The online Scrimba lecture can be found at https://scrimba.com/p/pWqLHa/cvNJyHd

**Comment by athif23** [comment]
I'm sorry, but I think it's scrimba's bug/error not imba. Please close the issue. Thanks.
