### ISSUE TITLE
Imba.setInterval not working as expected

### ISSUE THREAD

**Issue by PierBover** [imba/imba#202]
Apparently after each interval `Imba.setInterval` should do `Imba.commit` but this is not working as expected.

See this repro: https://scrimba.com/c/cdPNerTE

As you can see, with the commented `Imba.commit` in the `onInterval` function the tag is not re-rendered.

Am I missing something?

**Comment by somebee** [comment]
Does it fail for you locally as well? I'm not able to reproduce it in a local project, but the supplied scrim is clearly bugged :/

**Comment by PierBover** [comment]
Yeah it failed locally which is why I made the repro on Scrimba.
