### ISSUE TITLE
trigger data is null when supposed to be 0

### ISSUE THREAD

**Issue by CassianoSF** [imba/imba#203]
As we can see here: https://scrimba.com/c/cryRawAd

Nothing critical since there is workarounds like:

console.log e.data or 0

**Comment by somebee** [comment]
https://gitspeak.com/-/nsp2vsL26b7f9

Here is the crux of the issue:

https://github.com/imba/imba/blob/d8ed6998f6b8bfebc3949775509387536d4c67e9/src/imba/dom/event-manager.imba#L154-L158
