### ISSUE TITLE
[webpack]: Use Hot Module Replacement

### ISSUE THREAD

**Issue by scanf** [imba/imba#212]
The webpack integration can watch files and trigger compilation but that does not refresh the browser and you still need to manually do it after making changes. It would be great to add support for HMR to save on development time when developing Imba apps.

https://webpack.js.org/concepts/hot-module-replacement/

**Comment by somebee** [comment]
Crude HMR is supported just by passing `--hot` as an option when starting webpack-dev-server.

**Comment by scanf** [comment]
Will definitely be using that to speed up local development. Should we close this then and instead add a section in the docs?

**Comment by scanf** [comment]
We are moving away from webpack and the current template has HMR via rollup. Thanks.
