### ISSUE TITLE
Add support for decorators (annotations).

### ISSUE THREAD

**Issue by cstffx** [imba/imba#217]
### Description
Extend the syntax to support decorators. See this [document](https://github.com/tc39/proposal-decorators) for more details.

### Why
Imba code is clear, it should be productive in the backend. The idea appeared when I found this [example](https://github.com/imba/hello-world-imba/blob/master/src/server.imba). 

Decorators are frequently used by libraries used in the backend. For example TypeORM, the most mature ORM in the NodeJS ecosystem provides decorators to add metadata to entities, although its use is not mandatory it is an elegant and fast way. 

### Possible Implementation & Open Questions

Decorators are frequently designated using `@`. Since in Imba this character has a special meaning for the variables, the form used by others like C# could be more appropriate.

For example, for typescript we have:

```typescript
@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    firstName: string;

    @Column()
    lastName: string;

    @Column()
    age: number;
}
```

We could have for Imba

```imba
[Entity]
class User 

    [PrimaryGeneratedColumn("number")]
    prop id

    [Column]
    prop firstName

    [Column]
    prop lastName

    [Column]
    prop age 
```

**Comment by somebee** [comment]
I actually started on a branch long ago to implement decorator support using `@@decorator` syntax. We need to change how we build classes etc to make it work, but we're most likely going to start using native es6 classes pretty soon, which is an ideal time to sneak this in :)

**Comment by scanf** [comment]
See imba/imba#331undefined
