### ISSUE TITLE
Add click.right​ and handle contextmenu

### ISSUE THREAD

**Issue by aalemayhu** [imba/imba#218]
Currently `click.right` does not work but `click.left` works fine. From prior conversation with @somebee assuming this is due to the way the browsers treat context menus. I think it would make sense to cancel the context menu and call the right method for this case. This was reported by @Bohooslav on Gitter.

Scrimba cast for reproducer: https://scrimba.com/c/ca382VsP

### Example code

```imba
tag App
    prop counter
    def render
        <self.bar>
            # handler will be called when clicking button
            <button :click.right=(do counter++)> "Increment"
            <button :click.left=(do counter++)> "Increment"
            <p> "Counter of right click is {counter}"

Imba.mount <App counter=0>
```

**Comment by scanf** [comment]
@somebee from my notes on August 19th you mentioned `contextmenu.cancel` does not work. Should we open an issue for that?

**Comment by Athulpai12** [comment]
I would to take up this issue
