### ISSUE TITLE
Documentation: Explain @prop syntax

### ISSUE THREAD

**Issue by iamtirado** [imba/imba#221]
The @prop syntax is easy to use, and convenient, but @ symbol is confusing to me as to why we need it, when we need it, or if we need it. 
The prop state seems like it can be referenced with or without the @ symbol from within the tag.

```ruby
tag Switch
    prop state default: true
    def render
        <self>
            <button :tap=(do state=!state> #works
            <button :tap=(do @state=!@state> #works
            <button :tap=(do @state=!state> #works
```
They are called as an attribute without @ when the tag is instantiated.
```ruby
tag App
    def render
        <self>
            <Switch state=value>
```
As far as I know, Classes use the @ symbol as well for a different behavior.
I need a mental model that can be easily explained for others to learn when to use it, or not use it.

Q: Is the reason we have all the options is because a prop is essentially creating methods and variables, thus we can access them as variables or methods?

**Comment by scanf** [comment]
Please use the Imba.io repository for documentation related issues, moved it there for you. imba/imba.io#50

Thanks.
