### ISSUE TITLE
SPA router (hash based) for static sites

### ISSUE THREAD

**Issue by mphuie** [imba/imba#222]
### Description

imba-router requires a specific server-side side config. 

### Why

This severely limits useful of imba, static sites cannot be created with multiple routes. 

I use a lot of static hosting (Netlify, surge) and have stayed away from imba because I cannot route.

**Comment by scanf** [comment]
Love using Netlify and we are actually considering moving over imba.io there. 

This does not fit into the language repository, I will copy over your issue to somebee/imba-router which is still experimental.



Thanks.
