### ISSUE TITLE
Look into supporting the LSP protocol

### ISSUE THREAD

**Issue by scanf** [imba/imba#227]
> The Language Server protocol is used between a tool (the client) and a language smartness provider (the server) to integrate features like auto complete, go to definition, find all references and alike into the tool

https://langserver.org

**Comment by scanf** [comment]
I think this is well under way with all of the toolchain investments by @somebee. There is more left on the packaging but closing this as we have the separate repository

**Comment by predragnikolic** [comment]
Can we reopen this?

The https://github.com/imba/vscode-imba repo moved to the Imba monorepo https://github.com/imba/imba/tree/master/packages/vscode-imba.

I would love to see Imba support in other editors!
