### ISSUE TITLE
Support boolean attributes on tags

### ISSUE THREAD

**Issue by scanf** [imba/imba#234]
Adding boolean attributes to the input tag results  in runtime errors

```
<input placeholder="0x2A" disabled>
<input placeholder="0x7E4" enabled>
```

```
TypeError: _1(...).flag(...).flag(...).setEnabled is not a function
```

---

**Comment by Jefwillems** [comment]
I don't think enabled is a valid attribute so setEnabled does not exist?

**Comment by somebee** [comment]
This works in v2. I think it already works in v1, but as mentioned above, enabled is not a valid attribute.
