### ISSUE TITLE
Get an official mascot

### ISSUE THREAD

**Issue by scanf** [imba/imba#245]
For Imba v2 we are trying to get an official mascot. Below are some proposals from Torarin Jørstad, which ones do you like best? Please reply with either a screenshot of the versions or color and position.

Thanks.

---
![Imba - Red](https://user-images.githubusercontent.com/925044/69121008-7194b080-0a9b-11ea-8ce8-c7626279ba3f.png)
![Imba - Blue](https://user-images.githubusercontent.com/925044/69121016-748fa100-0a9b-11ea-97c1-cc7041561ed4.png)
![Imba - Purple](https://user-images.githubusercontent.com/925044/69121017-748fa100-0a9b-11ea-85f9-9775a1fb781a.png)
![Imba - Yellow](https://user-images.githubusercontent.com/925044/69121018-748fa100-0a9b-11ea-80ab-6322c3a0e8f5.png)

**Comment by Bohooslav** [comment]
Girls will like, but not me. And I do not understand why do you want this, neither React, nor Vue, nor Angular maybe do not have such a thing. I like your logo. Your logo is really cool when these birds are funny. You need something like a wing with wind between. I think that this image can be a
 good base for the mascot.

![45297010](https://user-images.githubusercontent.com/35796539/69151672-be9c7500-0ae3-11ea-93e7-02ad78a9dfbc.png)

**Comment by iamtirado** [comment]
It is fantastic work. 
If I had to pick, I'd say Yellow, Top.

On the idea of having a mascot at all...

1. I toyed around with creating a mascot last year in the logo design process, but as we went with an informal logo style, I thought that adding a mascot would push it further into a charming identity rather than preserving a bit of professionalism and class. 

2. Since the logo has its own wings, using it together with the mascot would be too busy and they would compete.

Most of the time, when I think of mascots, I think of third class, non-mainstream products that have sort of a cult-following. We may be just that at the moment, but that is not who we want to be.

Successful use of mascots, require a different type of branding where the logo and the mascot can play well together, for example mailchimp, or zurb foundation and its yeti. 

3. If we do go with a mascot, I would suggest simplifying significantly, and that it not be used in the logo or with it for the afore mentioned reasons, and that to me defeats the purpose of having one.

Anyhow, in the spirit of collaboration I am happy with different opinions, but those are my two cents. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iamtirado** [comment]
I guess I'll post the mascot ideas I had done. 
The idea here is to have a mascot that evolves as the the user advances through documentation.
But I just thought that it could instead evolve as Imba obtains certain numbers of github stars. 
![ImbaChicksEvolution](https://user-images.githubusercontent.com/13579055/69230231-73549600-0bb9-11ea-9881-1d937d3b5cf7.jpg)

**Comment by Bohooslav** [comment]
It is better. But remember that the mascot mast show to user the speed and
easy of Imba.

**Comment by olimart** [comment]
The 2 logos posted above look great.
Else, red, 2nd row, first on the left

**Comment by scanf** [comment]
Thanks for all your feedback and keep them coming.

**Comment by unplugandplay** [comment]
<img width="157" alt="Capture d’écran 2019-11-24 à 18 19 58" src="https://user-images.githubusercontent.com/6077/69498323-1de4f580-0ee7-11ea-87f5-df3d8d333d87.png">
That one is the best. But I agree the one proposed here show easing of the framework, not its celerity. Something representing a https://en.wikipedia.org/wiki/Bee_hummingbird would by the contrary represent agility , celerity and lightness which are the 3 reasons why I use Imba, not saying the main one the ruby like style ;) 
Or is that one the best bird to inspire from  https://en.wikipedia.org/wiki/Ruby-throated_hummingbird ?

**Comment by iamtirado** [comment]
Playing around a little bit.

https://scrimba.com/c/cggN6Tb

![image.png](https://gitspeak.com/-/nUp3ohL368206/image.png)

**Comment by Bohooslav** [comment]
Pretty good. Note that you may take away the black line if there is dark blue. Also, I note that on apple.com they use a huge range of font-sizes: from 10px even to 110px. Do not fear to make important things bigger. And do not forget to use font-family, which will support many languages and will not break the design.

**Comment by XANOZOID** [comment]
I feel like for an icon/avatar/mascot, Icarus in the iconic superman pose would be pretty cool. 

Icarus is the first thing that comes to my mind when I see the current logo

**Comment by scanf** [comment]
Hmm, looking at the alternative from Eric. It kind of reminds me of the [flash](https://en.wikipedia.org/wiki/Flash_(comics)), so starting to like it :smile:

@iamtirado can you add something like the Web components logo (hexagon shape) on the chest on your last example? Maybe Imba can be the project that makes Web components finally take off. What do you think?

![logo-192x192](https://user-images.githubusercontent.com/925044/72660015-14987680-39c8-11ea-9a27-446f39c99c7f.png)

**Comment by iamtirado** [comment]
Hmm. It doesn't fit the organic feel of the current brand, but I'll give some thought to that. 

I'm currently biased against incorporating the web components logo, but let me think about it. 

The main reason being, that for it to have any obvious link to web-components, it will have too be too similar and highly detailed, or else it won't really be obviously related to web-components. And I don't think it's a good idea to attach one brand based on the look of another. If they rebrand, you have to rebrand as well.  It will be more effective to mention web components up front on the website.

**Comment by Bohooslav** [comment]
.....................................

Богуслав would like to stay in touch on LinkedIn.

Богуслав Павлишинець
--
Ukraine

View profile https://www.linkedin.com/comm/in/%D0%B1%D0%BE%D0%B3%D1%83%D1%81%D0%BB%D0%B0%D0%B2-%D0%BF-114886156?trk=eml-guest-invite-pprofile-link-cta&trkEmail=eml-email_m2g_invite_single_01-null-426-null-null-%7E9if3uq%7Ek7yi4gn1%7Eoe-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BNR1X11m4QtGmXJgP43ZzMQ%3D%3D

Confirm that you know Богуслав https://www.linkedin.com/comm/start/accept-invitation?sharedKey=2bnWd3a0&invitationId=6646323458374459392&trk=eml-guest-invite-cta&trkEmail=eml-email_m2g_invite_single_01-null-423-null-null-%7E9if3uq%7Ek7yi4gn1%7Eoe-ssuw-start%7Esignup%7Ewarm&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BNR1X11m4QtGmXJgP43ZzMQ%3D%3D


.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-9if3uq-k7yi4gn1-oe&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_m2g_invite_single_01&li=434&m=unsub&ts=unsub&loid=AQF49yWhalY73QAAAXDx8M1cr5zgA2-4foAq6uZ2ptMFRbQj14HfmX2UabUe83JU8p61_thRgWsbELp5Zplnzkjs14SrCW2E_JBMxsmBuFEXH3HwogEhmbA_up7lDxKdwkhb-8C6REvL-tKyrK7Wld-lh_5X3FE5Gw&eid=-9if3uq-k7yi4gn1-oe

Help: https://www.linkedin.com/e/v2?e=-9if3uq-k7yi4gn1-oe&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BNR1X11m4QtGmXJgP43ZzMQ%3D%3D&a=customerServiceUrl&ek=email_m2g_invite_single_01&li=433&m=footer&ts=help&articleId=67


You are receiving Invitation emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to reply@reply.github.com.

© 2020 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by scanf** [comment]
Unless things change it seems like the bird has been picked.
