### ISSUE TITLE
Get syntax highlighting in rouge-ruby

### ISSUE THREAD

**Issue by aalemayhu** [imba/imba#246]
Dev.to uses rouge and this could help in getting syntax highlighting on their website.

> [Rouge](http://rouge.jneen.net/ "Rouge") is a pure Ruby syntax highlighter. It can highlight over 100 different languages, and output HTML or ANSI 256-color text. Its HTML output is compatible with stylesheets designed for [Pygments](http://pygments.org/ "Pygments").

https://github.com/rouge-ruby/rouge

**Comment by scanf** [comment]
https://rouge-ruby.github.io/docs/file.LexerDevelopment.html
