### ISSUE TITLE
v2 Slots - Slots have no regard for name

### ISSUE THREAD

**Issue by iamtirado** [imba/imba#248]
v2.0.0-alpha.9
All the Slot examples below get the .header style, which tells me they are all getting rendered as 
```
<slot name="header">
```
Example:
```
### css
.header {
	color: red;
}
###
tag box-element
  def render
    <self>
      <h1.header>
        <slot name="header"> 
          <em> "fallback header"
tag app-root
  def render
    <self>
      <box-element.one>
        <div slot="header">
            "hello"        
        <div> "Body Copy"
        <div slot="footer"> "Footer"
```
![image](https://user-images.githubusercontent.com/13579055/69907780-8dd70c80-140e-11ea-9605-ae2934d2da79.png)

**Comment by somebee** [comment]
Hmm, this looks like a pretty weird bug. In this case the expected behaviour should be that neither "Body Copy" or "Footer" should be rendered at all, right? Since you haven't defined the footer slot or default slot in box-element.

**Comment by iamtirado** [comment]
That's right. 
They could be simply rendered as a div if nothing else and throw an error for the slot property.
