### ISSUE TITLE
v2 Feature Request: Slots to Inherit from HTML element

### ISSUE THREAD

**Issue by ericvida** [imba/imba#249]
My last bug report, I was trying to style the contents of a slot, by wrapping the slot template in the desired element & class like this:
```
<h1.header>
  <slot name="header">
    <em> "fallback header"
```
This way, the implementation of the slot would then also be `h1` with the class of `.header`.
```
<div slot="header"> "This will be an h1 with class of header"
``` 
Is it possible to make it so that we can apply classes directly to the slot template like this?
```
<slot.header name="header">
  <em> "fallback header"
```
or allow it to inherit from native HTML elements

```
<slot.header as="h1" name="header"> # having "as" property to inherit from an element
#or
<h1.header name="header"> # having "name" property turns it into a slot.
# or
<slot.header name="header"> as h1
# or
<slot.header name="header"> < h1
```
Thanks

**Comment by iamtirado** [comment]
@somebee 

Have we landed slots? 

Should I close this issue?
