### ISSUE TITLE
default empty string as undefined

### ISSUE THREAD

**Issue by iamtirado** [imba/imba#257]
### Imba Version: ^2.0.0-alpha.10
```
tag web-app
	prop query default: "default"
	def render
		<self>
			<input[@query]>
			<p> @query
```
Paragraph will render "undefined". Shouldn't it render "default"?

**Comment by somebee** [comment]
Default props wasn't supported in alpha 10, and in the current version prop syntax is gone. Moving fast and breaking things :P Props are now defined using a field syntax - and you should be able to do it like this:

```imba
tag web-app
	@query = "default"
	def render
		<self>
			<input[@query]>
			<p> @query
```
