### ISSUE TITLE
v2: chaining modifiers not working

### ISSUE THREAD

**Issue by scanf** [imba/imba#260]
I think this has been mentioned before but just in case I am also creating this issue for follow up, see the example at test/index.html#apps/examples/scrollable-list.imba

Then try selecting any of the items, you should see a `TypeError` exception:

```
VM50:135 Uncaught (in promise) TypeError: Cannot read property 'done' of undefined
    at HTMLElement.toggle (<anonymous>:135:21)
    at EventHandler.handleEvent (index.js:21808)
```

**Comment by somebee** [comment]
Changed the syntax at some point + the example should be fixed now :)
