### ISSUE TITLE
V1(maybe v2?): Kebab-case styling is broken

### ISSUE THREAD

**Issue by XANOZOID** [imba/imba#261]
### Imba Version: 
^1.5.2

### Details
Presently, kebab-case css tags are not properly supported in imba. For example, if do

### Expected Behavior

I should be able to access my styles that use the kebab case.

### Actual Behavior

```css
.edit-tag { display: inline-block; }
```
and then import it
```imba
import {edit-tag} from './toggle-edit.css'
export tag toggle-edit
	def render 
		<self.{edit-tag}> <span> test
```

The generated style tag outputs this:
```css
.generic-toggle-edit__edit-tag--3bLi1 { display: inline-block; }
```
And the generated html for toggle-edit implements this:
```html
<div class="_toggle-edit">
```
So even if I was to do something like using a string for the class name, it'll never match that above. The compiler does not complain about the name or anything like that.

I also tried doing `import {editTag} from '...cs'` and trying that name out, but that also does not work.

### Your Environment

- Node 10
- Linux, Ubuntu Bionic (18.04.3 LTS) 

### Steps to Reproduce
I tried making a scrimba but importing css on scrimba wasn't working. 
Steps are as above.
1. Make a css file
2. Make a style with kebab case
3. Import it into an imba file and use it
4. It won't register

**Comment by XANOZOID** [comment]
Having taken a closer look, it's definitely starting to be related to webpack and the css loader. When I removed the `options` from hello-world-imba for webpack `css-loader`

```js
options: {
	modules: {
		mode: 'local',
		localIdentName: '[path][name]__[local]--[hash:base64:5]',
		context: path.resolve(__dirname, 'src'),
		hashPrefix: 'my-custom-hash',
	},
},
```
I'm able to start using the exact names from the css files (and the scoped SFC) styles. But this means the real problem is Imba isn't linking up correctly with this loader, right?

**Comment by somebee** [comment]
I haven't done much with css-modules in webpack etc. Have you tried using SFC in imba 1.5? You get scoped styles without these weird computed class names :)

**Comment by XANOZOID** [comment]
Yes! Ever since I made that comment I removed those options from the loader and have been using scoped css :smile:.  I would actually say this is a bug not related to "imba" as much as it is the helloworld setup I think! So this problem is not a concern from what I'm thinking . . . I do have a slightly related problem though, but I think it should be a new ticket
