### ISSUE TITLE
Syntax for decorators

### ISSUE THREAD

**Issue by somebee** [imba/imba#262]
Working on decorator support in Imba 2. We are currently using the `@@decorator` syntax, but it feels weird, especially when used with fields that also start with `@`. There are a few suggestion out there, but I propose that we try to keep the discussion here. Here are some alternatives I'm currently contemplating:

### Using `&` prefix

```imba
class Item
	&watch @field = 1

	&bench def method
		return 123
```

### Using no prefix

```imba
class Item
    watch @field = 1

    bench def method
        return 123
```

This is actually an alternative, since regular identifiers arent allowed in class bodies. Since decorators are imported and defined with regular identifiers it does make sense. The main problem is that it will be difficult to support class-level decorators with this syntax.

@scanf also suggested using `()decorator`. My main gripe with that is that decorators also supports arguments, and I think it looks a little weird with `()decorator(100)`.

**Comment by XANOZOID** [comment]
Here's my two cents. . .

```ruby

# This one doesn't seem bad. But exclamation might make shout "execute!" instead of "decorate"
class Item
	!watch @field = 1

# I'm not a fan of this one, but maybe it's easier to parse?
class Item
	[watch, decorator(...)] @field = 1

# Favorite, and gives me the impression these are 'augmentations' passed to the @field
class Item
	--watch @field = 1
        @field = 1 --watch --other --decorator(...)
        @field = 1 -w -o -dec(...)
```

I think I actually really like the idea of decorators/(modifiers?) as if they were optional command line arguments. Seems like a natural and expressive way to state "this is an optional augmentation". 

<del> I will edit this in case I'm off topic here, but I have a few things I'd like to add ..
If this is a decorator . . . does that mean it's being paired with extensions still (that I am aware exist in Imba 1)? </del> 

I just realized I might be thinking of a different type of decorator. I'll still leave what I said below here if I'm not completely off . . . 

(I was thinking of the decorator pattern when I asked this) Will/does Imba have a functionality for mixins? And, as a quick thought, would introducing some constructs in Imba for Aspect Orientated Programming be in for the run - to go even farther than decorating?

**Comment by scanf** [comment]
How about adding the arguments in the left hand side?

```imba
()freeze
()entity
class Player
	(auto: true)primarykeycolumn
	id\number
	(required: true)column
	birthYear\number
	(required: false)column
	birthMonth\number
	(required: false)column
	birthDay\number
	
	(false)enumerable
	def collectedItems
		self.items
```

**Comment by scanf** [comment]
There was some messages on Gitter regarding this. See screenshots below

![Skjermbilde 2020-01-18 kl  06 47 55](https://user-images.githubusercontent.com/925044/72659335-823fa500-39be-11ea-8c11-7fa900e231e4.png)
![Skjermbilde 2020-01-18 kl  06 48 05](https://user-images.githubusercontent.com/925044/72659336-823fa500-39be-11ea-9f60-5ca5894c9cd5.png)

**Comment by akaufmann** [comment]
How about a variation of Rust's [attributes](https://doc.rust-lang.org/reference/attributes.html)?
```imba
&[defineElement('app-post')]
tag Post
       &[length(10, 20)]
       @title = 'Post title'

       &[validator(customValidator)]
       @text = ''
       
       &[bench] def method
            return 123       
```

**Comment by XANOZOID** [comment]
I kind of like the syntax for thinking of it as a meta tag . . . `@:decorator`

**Comment by somebee** [comment]
Since we're now moving away from `@` as an alias for this it seems natural to use `@decorator` syntax.

**Comment by scanf** [comment]
Superseeded by imba/imba#331undefined
