### ISSUE TITLE
Current status of imba 2.0

### ISSUE THREAD

**Issue by somebee** [imba/imba#263]
We've been working on version 2 of imba for some time. To speed up the process we've decided to move development to master and actively encourage new users to start with v2, despite the fact that it is not _quite_ ready for primetime.

We will write more extensively about the changes in the coming weeks before official launch, but v2 includes a huge number of changes. The breaking changes will make migration from v1 very painful (until
migration tools are in place).

The reasoning behind all these changes will be discussed in the Imba Changelog casts on scrimba.com in the upcoming weeks.

## Improvements

- Future oriented syntax changes
    - Template strings
    - Object destructuring
    - Decorators
    - Iterators (for of)
    - Class fields
    - Private class fields
    - ES6 classes
    - ESM import/export
- Tag improvements
    - Support for slots
    - Support for fragments
    - Compiles to native web components
    - Consistent and performant mount/unmount
    - Dynamically named tags `<{object.type}>`
    - Functional tag components
    - Memoization everywhere
    - Improved event handling with modifiers++
    - **Insane** performance (details to come :P)
- Much smaller standard library

## Breaking changes

- Implicit self removed - use `self.identifier` or `@identifier`
- Implicit calling removed - use `()` to call methods without arguments
- Removed prop syntax - see new class field syntax and behaviour
- Symbols `:symbol` are deprecated - use strings instead.
- Keyed tags are now set using $key=mykey instead of @{mykey}
- Use `def constructor` instead of `def initialize`
- Use spread `...` syntax instead of splats `*`
- Use `static def method` instead of `def self.method`
- Class bodies are no longer executable

## Current limitations (to be rectified)

- Limited support for extending native tags
- No support for extending svg tags
- No support for server-side rendering
- Custom tags must be lowercase and include dashes
- Tooling even worse than with v1
- Advanced tag loops with multiple children are flaky
- Cannot define event listeners as methods like `def onclick`
- Touch support (`ontouchstart/update/end`) removed (to be replaced)

**Comment by scanf** [comment]
We also have much better source mapping now.

**Comment by scanf** [comment]
Server-side rendering has been rectified.

**Comment by scanf** [comment]
Closing in favour of imba/imba#328
