### ISSUE TITLE
Indentation - tabs or spaces

### ISSUE THREAD

**Issue by somebee** [imba/imba#265]
Time to revisit the never-ending debate. I have always been a fan of using tabs for indentation. I know I'm in the minority, and I also know that most editors default to spaces. The "inconsistent indentation" warnings are really annoying. I'm open for switching to 4 spaces in the imba source code, and recommend that as the default. For an indentation based language I think 2 spaces are too little (with tabs each individual can choose :P). We also need to add a formatter that can fix inconsistent indentation to the tooling (vscode-imba for v2 is the obvious first place to implement it).

What do you people think?

**Comment by XANOZOID** [comment]
I'm also a tab person myself.. a quick tap of the button and all the editors I've used seemed to have smart tabbing and the like. Spacing seems to be popular in a lot of places, but I personally - like you - prefer the fact that you can choose your own tab sizes and what not. I don't understand the usual argument against tabs... In my heart spaces are for spacing not indentation! 

For the whole error thing on vscode I just select all real quick and have a shortcut that links to turning spaces to tabs. A formatter you can right click on the page and use would be nice definitely.

**Comment by scanf** [comment]
Who really cares what the default is. As long as we have a tool that can enforce it. Maybe someone can make a CLI tool similiar to gofmt https://github.com/golang/go/blob/master/src/cmd/gofmt/gofmt.go

This way that function can be used in the VSCode extension and CLI users who prefer vim and company.

**Comment by iamtirado** [comment]
I use tabs also

**Comment by iamtirado** [comment]
@somebee Have we landed this discussion? Should it be closed?

**Comment by somebee** [comment]
Yep. The tooling and compiler still needs better error messages, but going forward Imba 2 will only support tabs :)

**Comment by ephetic** [comment]
Please don't make spaces a bug.

**Comment by Bohooslav** [comment]
If you are using VS Code, you can find there a cool tool for converting spaces to tabs. And I am sure that this feature is / will be available in other text editors as well,  so I do not think that this is a problem for you or for somebody else
