### ISSUE TITLE
Mount not called with props

### ISSUE THREAD

**Issue by nathanjohnson320** [imba/imba#270]
### Details

I'm working on porting material-imba to imba2 but run into a weird bug where the props are not passed into the mount function and the children are also empty.

In [this file](https://github.com/nathanjohnson320/material-imba2/blob/master/src/button/button.imba#L16) I define the button component and I use that component [here](https://github.com/nathanjohnson320/material-imba2/blob/master/src/app.imba#L13) with `@ripple` set to true but the mount function doesn't appear to get that value or the children so even if I hard code ripple to true it still errors out because `self.children[0]` is undefined.

### Expected Behavior

Mount function receives props and children

### Actual Behavior

Mount function has empty children and no props

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Windows 10, node.js 8.1): MacOS 10.15.2 (19C57), node v12.14.1
- Operating System and version (Mac or Linux): Mac
- Useful link to screenshot or any other information:
![image](https://user-images.githubusercontent.com/1680341/72764658-2724d280-3bb7-11ea-8f5d-860ac13b6e91.png)

### Steps to Reproduce

1. Create a component like [this](https://github.com/nathanjohnson320/material-imba2/blob/master/src/button/button.imba)
2. Call the mount function and log its props

### Stack Trace

</details>

**Comment by somebee** [comment]
Thank you for the report. Which browser are you using? Mount _should_ be called after rendering, but I will try to create a reproducer and fix this asap. You should also try to update to the latest version (alpha 19). If you want to chat about things you run into and/or have questions about undocumented v2 features please reach out to me on gitter :)

**Comment by somebee** [comment]
This turned out to be an interesting rabbithole. Fix with improved lifecycle behaviour is coming - probably tomorrow.

**Comment by somebee** [comment]
I just published alpha 20. Could you see if it works as intended now?

**Comment by nathanjohnson320** [comment]
@somebee that fixed the issue I was having thanks! 

I've run into another problem with the ripple effect but I'm pretty sure it's not imba related
