### ISSUE TITLE
Slot names break if they include dashes

### ISSUE THREAD

**Issue by nathanjohnson320** [imba/imba#272]
### Details

Declared a component with a slot named "header-title" and it throws the error `Uncaught ReferenceError: title is not defined` because in the dist code it looks like it's compiled into `t$4=t$0.__slots.header-title;` and title isn't a variable so it breaks.

### Expected Behavior

Naming slots with dashes doesn't throw errors

### Actual Behavior

Slots with dashes throws errors

### Possible Fix

As an interim fix I removed the dashes but ideally shouldn't have to do that.

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Windows 10, node.js 8.1): MacOS 10.15.2, node v10.17.0, Chrome  79.0.3945.117
- Operating System and version (Mac or Linux): Mac
- Useful link to screenshot or any other information:

### Steps to Reproduce

1.  Use this sample code in a tag 
```
<self
      .mdc-drawer
      .mdc-drawer--dismissible=@dismissable
      .mdc-drawer--modal=@modal
    >
        <div .mdc-drawer__header>
          <h3
            .mdc-drawer__title
          >
            <slot name="header-title">
          <h6 .mdc-drawer__subtitle>
            <slot name="header-subtitle">
      <div class="mdc-drawer__content">
        <slot name="content">
```
2. Console should have error

### Stack Trace

```
drawer.imba:30 Uncaught ReferenceError: title is not defined
    at HTMLElement.render (drawer.imba:30)
    at HTMLElement.render (docs.imba:27)
    at HTMLElement.connectedCallback (index.imba:410)
    at ImbaElementRegistry.define (index.imba:162)
    at docs.imba:39
```
</details>

**Comment by somebee** [comment]
Fixed this morning. Will deploy new alpha later today.
