### ISSUE TITLE
Mount not being called

### ISSUE THREAD

**Issue by nathanjohnson320** [imba/imba#273]
### Details

I am using [this drawer tag](https://github.com/nathanjohnson320/material-imba2/blob/master/src/drawer.imba#L16) and console logging in the mount but the log is never fired when I use it [here](https://github.com/nathanjohnson320/material-imba2/blob/master/src/docs.imba#L27)

### Expected Behavior

Mount should be called for this tag

### Actual Behavior

Mount is not called.

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Windows 10, node.js 8.1): MacOS 10.15.2, node v10, Chrom v79
- Operating System and version (Mac or Linux): Mac
- Useful link to screenshot or any other information: 

### Steps to Reproduce

1.  Import [the tag](https://github.com/nathanjohnson320/material-imba/blob/master/src/drawer/drawer.imba)
2. Render the tag [like this](https://github.com/nathanjohnson320/material-imba2/blob/master/src/docs.imba#L27)
3. Check console for logs

### Stack Trace

</details>

**Comment by somebee** [comment]
Oh, this hasn't been communicated well. mount/unmount is currently not supported when inheriting from native elements. We're using web components connectedCallback and disconnectedCallback for mounting. There are ways around it, but will probably take some time to support. Web Components has support for this with "Customized built in elements", but safari has stated that they are not going to implement that part of the api. So, we need another workaround

**Comment by nathanjohnson320** [comment]
Ah ok, I noticed on a couple others that I could get around it by nesting the children under self and that appears to work ok so I'll keep doing that.

So instead of 
```
<self
    .mdc-drawer
    .mdc-drawer--dismissible=@dismissable
    .mdc-drawer--modal=@modal
>
```
I do
```
<self>
      <aside
        .mdc-drawer
        .mdc-drawer--dismissible=@dismissable
        .mdc-drawer--modal=@modal
      >
```
And then I can use `MDCDrawer.new self.children[0]` instead of `MDCDrawer.new self`
