### ISSUE TITLE
If and Elif branch in the render method can be rendered simultaneously

### ISSUE THREAD

**Issue by akaufmann** [imba/imba#278]
### Imba Version: 2.0.0-alpha.25

If you have an `if` and an `elif` in the render method, it may happen that both branches are rendered.
https://scrimba.com/c/crm9reC6

**Comment by somebee** [comment]
Started working on a fix now. Need to fix some related performance issues so it might take a couple of days before fix is merged. Thanks for reporting :)

**Comment by somebee** [comment]
Pushed a new version with fix now. Also improved performance and logic of conditionals inside render trees :)
