### ISSUE TITLE
How do we use prop watch in Imba v2?

### ISSUE THREAD

**Issue by aalemayhu** [imba/imba#279]
I tried doing something like the below but it did not work. I am assuming this not implemented yet, right?

```

tag reactive-declarations

        @count = 1 watch: yes
        [...]
        def countDidSet new, old
            console.log('new', new)
            console.log('old', old)
        [...]
```

Thanks.

**Comment by somebee** [comment]
Watch will need to be implemened using decorators. Scheduled for v2. Hopefully we can land it late next week :)

**Comment by scanf** [comment]
Ah, thanks.
