### ISSUE TITLE
v2: conditional statement not working properly from method in render

### ISSUE THREAD

**Issue by scanf** [imba/imba#281]
A button disappears when it's supposed to be visible, see code below and Scrimba playground. Am I missing something?

Playground: https://scrimba.com/c/czkyW9uM

```
tag if-blocks
	
	@user = { loggedIn: false }

	def toggle
		@user.loggedIn = !@user.loggedIn

	def loginButton
			if @user.loggedIn
				<button :click.toggle()> "Log out"
			if !@user.loggedIn
				<button :click.toggle()> "Log in"

	def render
		<self> 
			self.loginButton()


### css
app-root {
	margin: 1rem;
}
###
tag app-root

	def render
		<self>
			<h1> "Issue with if blocks"
			<if-blocks>
```

Thanks.

**Comment by somebee** [comment]
Reproduced it here. Will look into it :)

**Comment by somebee** [comment]
Hmm, I'm not sure this is really a bug. When the two items in loginButtons are not wrapped in a fragment, it is like a regular function, where only the expression will be returned.

```imba
# essentially like this:
def loginButton
	if loggedIn
		true
	if !loggedIn
		return false

# alternative that would work:
def loginButton
	if loggedIn
		<element>
	else
		<other>

# This is beside the issue, but I would implement the example like:
tag app-root
	def render
		<self> 
			<button :click.toggle()>
				@user.loggedIn ? "Log in" : "Log out"
```

**Comment by scanf** [comment]
I see, it works this way. I will just use the return keyword more. Thanks.

**Comment by somebee** [comment]
Explicit return might introduce some weird issues with tag loops etc (nice if we catch them). In this case I'd change the last if to an else (or an elif).
