### ISSUE TITLE
v2: Prop inheritance issue

### ISSUE THREAD

**Issue by ericvida** [imba/imba#282]
I would think that the tag instance prop/attr value should override the default tag prop/attr value, but it doesn't.
Is this expected behavior? Being able to inherit default prop/attr values, and override them at the instance,  would enable some really neat capabilities.
```imba
tag inherit-from
	def render
		<self style="border-color: green;"> # overrides inline style in my-component
			<slot>

tag my-component < inherit-from
	def render
		<self style="border-color: blue;"> # overrides inline style in app-root
			<slot>
tag app-root
	def render
		<self>
			<my-component style="border-color: red;"> # should this override or no?
				<p> "hello"
```

[Scrimba cast here](https://scrimba.com/c/cgMPaZUa)

**Comment by somebee** [comment]
It's not really a bug, but I agree it is unexpected. Will think about how we can support it.
Btw, this issue makes gitspeak crash for some reason, so I'm digging into that first :P

**Comment by iamtirado** [comment]
>It's not really a bug, but I agree it is unexpected. Will think about how we can support it. ...

@somebee Funny, i posted the issue from gitspeak. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iamtirado** [comment]
@somebee Was this issue solved?
