### ISSUE TITLE
Allow setting flags directly on tags (outside of render)

### ISSUE THREAD

**Issue by somebee** [imba/imba#286]
If you start adding / removing classes manually via classList now it will interfere with rendering. The class changes you make manually will be overridden whenever the declarative classes change. Example:

```imba
tag app-root
	def addSomeClass
		@classList.add('some-class')

	def render
		<self.app.desktop .logged-in=@user>
			<div> "..."
			<button :click.addSomeClass> 'Add class'
```

In the example above `some-class` will be added correctly to app-root upon pressing the button, but when user logs in/out the rendering tree will update the classes of app-root, removing `some-class`. It might not be good practice to add classes outside of render, but see quite a few cases where it makes sense.

**Comment by scanf** [comment]
Let's take a look at this on Wednesday, thanks.
