### ISSUE TITLE
Support index variable in for of

### ISSUE THREAD

**Issue by somebee** [imba/imba#289]
Do you think we should support a magical index variable in for of loops?

```imba
for item of array
	item * 2
```

currently compiles to

```javascript
for (let item of array){
	item * 2;
};
```

We could support an optional index argument like

```imba
for item,i of array
    item * 2 + i
```

which would then compile to

```javascript
let i = 0
for (let item of array){
    item * 2;
	i++;
};
```

Would you find it useful? For me it definitely is.

**Comment by iamtirado** [comment]
don't we currently have 
`for key, item of array?`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iamtirado** [comment]
>Do you think we should support a magical index variable in for of loops? ...

@somebee totally could use that.
   

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by altteo** [comment]
I used indexes a lot. This is a must have feature!
