### ISSUE TITLE
Function error Imba 2.

### ISSUE THREAD

**Issue by iamtirado** [imba/imba#295]
I get randomize is not defined. I feel like I remember putting functions and methods inside the tag before. undefined

```imba
tag app-root
	def randomize
		Math.random()
	def render
		<self>
			console.log randomize()
```

Error

```console
Uncaught ReferenceError: randomize is not defined
    at HTMLElement.render (app.imba:7)
    at HTMLElement.connectedCallback (index.imba:426)
render @ app.imba:7
connectedCallback @ index.imba:426
```

Not sure if this is an imba issue or a imba2-hello-world issue.

**Comment by somebee** [comment]
Remember, implicit self is currently removed from v2, so you would need to write `@randomize()`. We are contemplating enabling it again, but there are downsides to both approaches :)

**Comment by iamtirado** [comment]
ahh. i figured it had to do with that. i didn't know the syntax. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iamtirado** [comment]
closing this as it's not really a bug. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
