### ISSUE TITLE
Compiler inserts imba import with the wrong path on Windows

### ISSUE THREAD

**Issue by altteo** [imba/imba#300]
![image](https://user-images.githubusercontent.com/1933862/74864019-e3f98300-535f-11ea-8488-70e16ff13682.png)

Must be 
`import 'D:\_Projects\imba2-template\node_modules\imba\src\imba\index';`
or better
`import './node_modules/imba/src/imba/index';`

**Comment by altteo** [comment]
The mess is only with absolute paths. Relative paths work the same on any OS. If the absolute pass is used (why we need it???) it mast be composed with path.join

**Comment by somebee** [comment]
I'll take a look. Thanks for reporting

**Comment by altteo** [comment]
I don’t think it is a good idea to make Imba compiler node-dependent. It is a rollup thing to make compiled code work.
The new thing is Deno (from creator of node). It doesn’t not have package manager at all. Packages are available through url. So I suppose compiler should be future-ready. And we can do different rollup versions - for node and for Deno.
Or we can do Deno-way from very beginning as we go away from common bundlers like webpack (they are very node-dependent). Deno also can bundle out of the box.

**Comment by altteo** [comment]
Deno does not have compiler api yet (to plug own compiler), but it should be implemented before version 1.0. So it is a good idea to have node-independent compiler ready.

**Comment by somebee** [comment]
The actual compiler is still not dependent on node. With minor changes it should be possible to compile imba files to esm that works directly in browsers (without using any bundlers). Rollup just feels like the cleanest alternative for bundling atm.

**Comment by somebee** [comment]
Btw, I'll make sure the paths are relativized.

**Comment by scanf** [comment]
Similar to #302, fixed in https://github.com/imba/imba/commit/541cdb55e22fb08194ed2d8ae8c11394ca5d99b7
