### ISSUE TITLE
Making <self> optional in render

### ISSUE THREAD

**Issue by somebee** [imba/imba#305]
Ref discussion started by @iamtirado [here](https://users.imba.io/t/can-self-be-optional/53/2).

The proposal is to allow dropping self inside render if you're not setting any classes etc on it:

```imba
tag app-item
	def render
		<header> "Hello"
		<section> ...
```

I see the point in that it removes one level of indentation and looks nice. My main problem with it is that it can only behave this way inside methods called render. That seems a little too magical. One alternative could be to allow the render defined directly on the tag?

```imba
tag app-item
	def toggle
		...
	
	<self>
		<header> "Hello"
		<section> ...
```

What would you think about this approach?

**Comment by akaufmann** [comment]
> One alternative could be to allow the render defined directly on the tag?

Mmh, since it is specified differently than methods, it looks a bit strange in my eyes to put it on the same level - for me it always looks like a part of the HTML tags. It would be nice if it was implicit. 

Or what about  `<self>` on the same level as the top-level HTML tag? †

```ruby
tag app-item
	def toggle
		...
	
	        <self>
		<header> "Hello"
		<section> ...
```

_Another thought:_
What about a new `<html>` tag  that could be used in methods/const/vars/... - I've always wished I could specify HTML tags everywhere, like in React? †

```ruby
const footer = <html>
	<div> "Footer"
	<div> "More footer content"

tag app-root
	def header
		<html>
		<div> "Header"
		<div> "More header content"

	def render
                @header()
		<div> "Hello from root" 
                footer
```

† I have to admit that `<self>` was/is always a little blackbox for me. Maybe that's why the suggestions are not possible.

**Comment by altteo** [comment]
Why we need self at all? It looks a little bit magic by itself. As I understand you have implemented it to exclude situations for example when tag is made from p but renders img on the root level. Like this:

```
def MyTag < p
    def render
        <img>
```

But is it really needed to make tag from “p” `tag MyTag < p?`? Could we move all html element magic inside render `<p>`? In this case when we do not inherit Imba tag from some magic classes (div,p,img) we could put tag it self in place of self.

```
def tag
    def render
         <p>
```

**Comment by altteo** [comment]
I mean we do not have any benefits on Imba level when inheriting tags. I assume it was needed solely for compiler, but compiler could do its magic considering the root level of render function. And I suppose we do not need any tag-specific magic.

**Comment by altteo** [comment]
And the problem is not in intention level. The problem is that <self> is not a common html tag. It feels some alien-ish :-)

**Comment by altteo** [comment]
So I’m certain that we do not need self at all. Maybe we could even go further and make some keyword `html` like you proposed in css-related topic. So we can do several functions and it could close slots problem this way:

```
tag MyDiv
    
     html slot1
        <div>
             <p> “hello”
     
      html body # default rendering function
       <div>
             <slot1>
```

But as for me it will make code difficult to understand, so i’d prefer to stick to just one render function.

**Comment by altteo** [comment]
And by the way if drop self in render function we will be able to use many root tags:

```
def render
   <div>
   <p>
   <img>
```

This way Imba tag will not be some html tag related or tangled. It will be readable and reusable chunk of code from which we could very fast render html (and hope css) the way we wanted.

**Comment by scanf** [comment]
Also talked about here https://scrimba.com/p/pdq9quP/ceMbzNhW

**Comment by iamtirado** [comment]
Great solution with <self>

It saves horizontal space and it makes sense.

Maybe in the future we can have a magical <styles> tag to go along with it

```imba
tag my-app
	<self>
		<h1> "Hello World"
	<styles css scoped>
		h1 {
			font-weight: bold;
		}
```
