### ISSUE TITLE
inline css feature

### ISSUE THREAD

**Issue by ericvida** [imba/imba#312]
Currently this is possible:
`<div css:display='block'>`
But we cannot do multiple values at the same time like this
`<div css("display='block'", "border: 1px solid blue;")>`
A syntax like above would also be helpful for dynamic styles and styled component frameworks.
```ruby
let bg = "background-color: red;"
let b1 = "border: 1px solid red;"
`<div css(bg, b1)>`
```

**Comment by Bohooslav** [comment]
We already has inline CSS: `<div css:display='block'>` and `style="display: block; {some very useful Interpolation and &c}"` and I think that it is pretty enough, at least for me.

**Comment by iamtirado** [comment]
The above are not so pretty for dynamic styles.

However, i did find that I can do this: `style=bg+b1` That's pretty neat.

`css(bg, b1)` would be neater in my opinion. But it's fine.

**Comment by Bohooslav** [comment]
Take a look at this => https://scrimba.com/c/cEKqnVSB

**Comment by iamtirado** [comment]
I'm really looking forward to being able to do this with imba one day. @somebee 

```imba
let theme =
	primary: 'tomato'
def color val
	"color: {val}"
tag app-root
	<self>
		<h1> "Hello World!"
	<style css scoped>
		h1 {
			color(theme.primary)
		}
```

**Comment by Bohooslav** [comment]
🤯

**Comment by iamtirado** [comment]
You could make some really amazing style frameworks with functionality like this.
