### ISSUE TITLE
HTML tag attributes

### ISSUE THREAD

**Issue by altteo** [imba/imba#316]
I need to make an HTML tag contenteditable. But the only way I could find out is to set html tag directly on button click (not even on creation). 
1. We need some technique to implement needed attributes  for Imba tags. Like it was in Imba v.1. with "attr" keyword.
2. We need any attribute of the HTML tag (in render function) pass directly to HTMLElement

**Comment by iamtirado** [comment]
@somebee replied in the chat that you can do it with contentEditable="true"

**Comment by scanf** [comment]
As suggested above you can pass in the attribute you want. Either custom ones or the existing ones.
