### ISSUE TITLE
Add Instructions for running test suite to readme (or another doc in repo)

### ISSUE THREAD

**Issue by JulienMLan** [imba/imba#324]
### Description
 Right now there is no documentation on how to run tests for this repository, It would be great if a simple document/ section of the readme could outline how to run the tests locally

### Why
this would make it faster for people to dig into the compiler and understand it by observing the effects their changes have on tests. It would also support good, tested contributions by making it really easy to get started writing tests and running them! 

### Possible Implementation & Open Questions
Already Kind of touched on this, but we can make a tests.md file, or just append a section to the lower-regions of the readme that goes over how to locally run tests

### Is this something you're interested in working on?
yes, If I figure out how to run the tests locally I will spin up a PR to add this

**Comment by scanf** [comment]
Sounds good, would appreciate if you could cook something. Below is a quick draft I did, that maybe you can use as basis? Feel free to discard also, but I would prefer it if you add the new file in `test/README.md`. 

# The Imba Test Suite

Imba is [self-hosted][sh], which means that the language is written in Imba.


This document let's you know how to get started quickly.

The Imba test suite uses puppeeter among other thi


Before you can start running the tests you need to have a version of Imba setup:

```
yarn bootstrap # npm run bootstrap
```

## Adding a New Test

TODO

## Running A Single Test

TODO

## Running All The Tests

Depending on your system it might take a while to run the tests

```
yarn test
```

## Troubleshooting

Make sure you have installed the development dependencies for Imba

```
yarn # npm install
```

If for some reason the tests are taking what seems like forever or your
changes are not being applied try to purge the dist directory

```
RESET=true yarn test
```

[sh]: https://en.wikipedia.org/wiki/Self-hosting_(compilers)

**Comment by scanf** [comment]
@JulienMLan courtesy, ping.
