### ISSUE TITLE
Latest status

### ISSUE THREAD

**Issue by somebee** [imba/imba#328]
Here comes a quick update regarding Imba 2. I've recently started to use v2 for actual projects (finally), and it made me realize a bunch of things that did not sit right with me personally. So I've been tweaking syntax++ and I can now say that it is starting to feel _right_. Good thing we are in alpha, because there are a bunch of breaking changes to come still.

First off, the way Imba was originally developed was in a very tight feedback loop – created and modified alongside the first application that used the language. This allows for a lot of freedom to play around and experiment to hopefully end up with a language that is very intuitive and useful in _practice_. At the same time it makes the development appear very chaotic from the outside, and it is difficult for external contributors to keep up with the rapid changes. It is very much the opposite of _"designed by committee"_.

I want to improve the development process and open it more up. @scanf has been of tremendous help here already, arranging bi-weekly community meetings and taking charge of releasing Imba Changelog episodes on scrimba. Still, I often succumb to developing and experimenting in private, dogfooding and changing the language daily as I use it to tackle real projects (like rewriting scrimba and gitspeak in v2). The development will likely still follow this pattern until v2 is stable and released. I'll always strive to open up, but just want you to know that if I go silent and progress seems to have stopped, I'm probably just experimenting and dogfooding – trying to make v2 the best it can be.

# Recent changes

### Implicit self is in - `@` is out

This was a major thing. Using `@` as a shorthand for self felt at times awkward and arbitrary. Especially for special identifiers like `@$internalThing` and `@_someProp`. After turning implicit self back on and using it for a while I'm confident that this will not change _again_ for v2. Implicit self will still require slightly better documentation and might take some time getting used to, but the tradeoffs are worth it. So, no more `@identifer`, just use `identfier` or stay explicit `self.identifier` if you prefer. There are predefined globals like `window` and `document` as in v1. For other globals you can access `global.identifier`.

### Method `invocation!`

To invoke methods without arguments in v2 you can use the `!` exclamation mark. You can still use parens, but I urge you to actually try it for a while before you judge it :) Very unlikely to change before final v2.

## Tooling

VSCode will be the recommended editor for v2, and we have now published a new imba extension for vscode (Just called Imba when you search in vscode extensions). This is already pretty great! Good autocompletions and type inference based on typescript tooling, and also goto definition, html docs for tags/attributes and much more. Still working on this every day. Will show more of this in the next community meeting.

# Upcoming changes

### Remove private fields?

Right now Imba supports private fields (`#private`), but it is compiled to regular public properties with a prefix. After reintroducing implicit self it is starting to feel like a superfluous feature. One might as well just use underscored `_private` identifiers for these private things, and/or `$` prefix for internal stuff. We should discuss this - but my vote is for removing private fields for v2.

### Decorators

Now that we're done with `@` as an alias for `self` we can finally use it for decorators. This is next on my list.

### Remove `predicate?` methods?

Recently introduced this together with `dangerous!` methods, inspired by ruby. In real use I'm still a fan of this, but there are some challenging aspects that need to be worked through. It _might_ be removed for v2 final, so until then it is smarter to stick with your `isPredicate` methods.

### Tags vs web components

The tooling and core language is finally at a point where I really enjoy writing v2 code. There are still many challenges with tags, especially creating custom tags that inherit from native ones, like an `app-button` or `user-form`. This is one of the next things I'll try to tackle.

### Scrimba fixes

The version on scrimba lags behinds now. After adding the decorator support we'll update the version on scrimba again. Hopefully this weekend.

**Comment by iamtirado** [comment]
Thanks for this clear update.
