### ISSUE TITLE
Update decorator syntax

### ISSUE THREAD

**Issue by somebee** [imba/imba#331]
Will now use `@` to prefix decorators like in es6

**Comment by shishtpal** [comment]
I think It would be nice If we stays with es6 syntax, so we don't have to worry like `:` and `.`

**Comment by somebee** [comment]
Changed how decorators are defined. You can now export and import decorators like everything else. Any method starting with `@` is treated as a decorator.

```imba
# decorators.imba
export def @log target, key, descriptor
	let value = descriptor.value
	descriptor.value = do
		console.log("called {key}")
		return value.apply(this,arguments)
	return descriptor
```

```imba
# app.imba
import { @log } from './decorators'

tag user-item
	@log def render
		<self> ...

```

I'm still trying to come up with a good way to allow passing options to decorators without having to think about whether something is a decorator or a decorator factory (see https://www.typescriptlang.org/docs/handbook/decorators.html). It is subject to change, but right now, any arguments you pass into to decorators will be exposed on self/this in the decorator method.

```imba
# app.imba
def @readonly target, key, descriptor
	let bool = this[0] isa Boolean ? this[0] : yes
	descriptor.readonly = bool
	return descriptor

tag user-item
	@readonly def one
		self

	@readonly(no) def two
		self
```

It isn't perfect, but with some tweaking I think it will be much better than differentiating between decorators and their factories. Also contemplating some shorthand syntax for adding modifiers to decorators - like the event syntax. So `@decor.async.something` would call the `@decor` decorator, but the flags `{async: true, something: true}` would be accessible within the decor context.

It works very well with vscode autocompletions and auto-importing:
![2020-04-04 12 06 32](https://user-images.githubusercontent.com/8467/78424323-125fc300-766d-11ea-9596-4a5466151da1.gif)
