### ISSUE TITLE
Make multiline comments follow indentation?

### ISSUE THREAD

**Issue by somebee** [imba/imba#337]
Since everything else in imba respects indentation, does it make sense to make multiline comments follow indentation as well? Ignore the closing `###` in the following examples

```imba
### some comment
	Everything inside here is commented
	But it respects indentation ###
<div> "This is not commented"
```

It would be a very nice way to quickly be able to comment out methods, conditionals, and tag trees. It allows you to prepend any chunk with `###` to comment out the whole chunk (with its indented children)

```imba
tag app
	def render
		<self>
			<div> "hello"
			### if true
				<section.something> ###
			<footer>
				### <ul.list>
					<li> 'home'
					<li> 'about' ###
				<div> 'yes'

	### def setup
		yes ###
	
```

**Comment by iamtirado** [comment]
I agree with that.
Comments and CSS break the indentation syntax. 
But do we need the ### at the end?
```
### Comment Block
    Couldn't this potentially
    be a comment block
    without the need of closing hashes?
```

This would pave the way for indented css
```
### css
    app-root
         color: red;
```
Also why can't we just use js comments? They're easier to type.
Here's how we used them in pug. It was great.
![image](https://user-images.githubusercontent.com/13579055/80248148-338c5180-8624-11ea-9e0e-08cad73640db.png)

**Comment by somebee** [comment]
`//` is actually supported in v2 now. The main reason we might need to differentiate between regular comments and multiline comments is that this usecase ought to be supported:

```imba
if true # inline comment
	doSomething
```

In this case the indented content should not be commented out. Sure, we could say that it will be commented out only when the comment starts the line. Hmm, so maybe we should use `//` for everything, and have it also respect indentation when it is at the start of the line?

As for css - I'm thinking _a lot_ about how to improve that experience :)

**Comment by somebee** [comment]
For comments you want to output in rendering it might make sense to support regular html comments?

```imba
<div>
	<!-- dom comment -->
	<span> 'hello' 
```

**Comment by iamtirado** [comment]
@somebee 
How about
// Imba / JS comments
//- Imba only comments
<// html comment >

**Comment by Bohooslav** [comment]
I think multiline comments will be very helpful, html comments are needless

**Comment by iamtirado** [comment]
My only reason for supporting html comments is for when some library might need html comments. I can't think of one right now, but I know they exist. Also for things like conditional comments based on browser being used.
