### ISSUE TITLE
Change event binding syntax from `:click` to `@click`?

### ISSUE THREAD

**Issue by somebee** [imba/imba#345]
## Benefits

- More visually different from classes. `.click` and `:click` looks very similar on first glance.
- Frameworks like tailwind uses `:` in classnames
- You can use `:` for special props like `<div bind:value=...>` and potentially in classnames (eg. tailwind).
- Colon could in the future be used for styling feature like hover-state class names. Where you could do `<div @click.something :hover.bg-gray-300>`to state that while the hover pseudostate is true, element should have bg-gray-300 class.

## Drawbacks

- Possibly be confusing that it looks like decorators

**Comment by iamtirado** [comment]
I'm ok with that. :)

**Comment by somebee** [comment]
Landed this in the latest release. `:` still works, but will likely be removed before v2 final.
