### ISSUE TITLE
Is it possible to Extend a Class Constructor?

### ISSUE THREAD

**Issue by ericvida** [imba/imba#351]
I'm not sure if it's supposed to be a feature or not. I observed that Constructors of a class cannot be extended. Just pointing that out in case it's supposed to be a thing. 

```imba
class Person
    def constructor name, age
        name = name
        age = age

class Athlete < Person
    def constructor trophies
        trophies = trophies
```

**Comment by iamtirado** [comment]
Wait. I noticed that if I use super() to pass all the previous arguments It will work, but I don't see the benefit of extending the parent Class, if I have to repeat all the arguments. 

I'm wondering if it would hurt an anything to have super() called under the hood.

```imba
class Person
	def constructor name, age
		name = name
		age = age
class Athlete < Person
	def constructor name, age, trophies
		super(name, age)
		trophies = trophies
let Eric = Athlete.new "Eric", 30, 20
console.log Eric
```

**Comment by somebee** [comment]
Writing `super` without arguments will automatically pass through arguments. Since calling super in constructor is mandatory in es6 we could automatically add it, but is it bordering on too much magic?

**Comment by iamtirado** [comment]
> Writing `super` without arguments will automatically pass through arguments. Since calling super in constructor is mandatory in es6 we could automatically add it, but is it bordering on too much magic?

I don't think it's too much magic. But I'm relatively new to using constructors.

It falls into the same category as not having to use the "Async" function keyword for me.

What can it possibly hurt to pass super() magically and let people write it manually if they want. 

If it happens under the hood it will have the same experience as when extending methods.

If it wasn't for needing super() i could have guessed how to extend the constructor after learning how to extend methods.

**Comment by iamtirado** [comment]
@somebee

**Comment by somebee** [comment]
I'll consider adding it automatically. That said, it is not the same as overriding regular methods. If you don't call super inside a regular method it will never call the parent function, but in constructors you must. So inside athlete constructor, the parent constructor will always be called as well. If it is added automagically that might not be obvious to people?

But yes, I'm inclined to automatically add it. Right now it doesn't even throw a warning if you forget, which is definitely not acceptable :)

**Comment by iamtirado** [comment]
I see. I just think that if I'm extending a class, i want to inherit it's constructors by default. 
It would make sense not to pass super by default if there are times when you want to inherit props and methods of a class, but not it's constructors.
How common is that? 

The only reason I would want to manually pass the parent arguments is if I could control when the parent constructor arguments are passed in the argument array, like do I want my new constructor arguments at the end of the argument array or before. Does that make sense? something like this. 

```imba
class child < parent
   def constructor super(), new
      new = new

let Eric = Athlete.new "New argument", "old", "old"

```

or 

```imba
class child < parent
   def constructor new, super()
      new = new
let Eric = Athlete.new "old", "old", "new"

```

But maybe that's not something that should be customizable, or there's already an expected behavior that shouldn't be tampered with. 
@somebee

**Comment by Spaceghost** [comment]
Please keep to being rubyish for this. Use super, allow subclasses and Mixins to control whether they call super and how they call super but don’t call it for them.
