### ISSUE TITLE
Interview

### ISSUE THREAD

**Issue by brucou** [imba/imba#364]
Hi @somebee ,

I am a news editor for [InfoQ](www.infoq.com). Would you be interested in an interview on Imba, its motivation, design principles and value added?

You may not necessarily know InfoQ so let me tell a few quick things about it. InfoQ's mission is to help dev teams adopt new technologies and practices. InfoQ's particularity is that content is written by software engineers/professional developers over professional writers. Our primary audience are tech leads, senior developers and software architects.

We regularly do interviews (see [example interview with Rich Harris, Svelte creator](https://www.infoq.com/news/2019/05/svelte-3-interview-rich-harris/)) on a variety of subjects. Let me know if that is of any interest to you. I hope this finds you well and safe in these troubled days.

Kind regards

**Comment by somebee** [comment]
Hey :) Could you contact me on sindre [at] identu [dot] no?
