### ISSUE TITLE
Idea: Compiling Static Pages from Imba for better SEO

### ISSUE THREAD

**Issue by ericvida** [imba/imba#365]
In discussion with a friend I'm collaborating on a project with, we realized that another big issue in web applications that have content generated at run time, is that they don't rank well on search engines. Search engine crawlers look at static files, and not dynamic content if I understand that correctly.

Just dropping this thought here before I forget about it.
Maybe one day, Imba could solve this one day, by having the option to compile to html one day.
```
tag about-page 
    static
        about.html
    def render
        <self>
            <nav-bar>
            <content>
                <markdown-file>
tag app-root
    static
        index.html
    <self>
        <nav-bar>
        <content>
```
I'm not sure if Imba will ever want to go this route. Maybe Search engines will eventually rank web apps better one day. I don't know what might go into making this happen. Just thought I'd drop the thought here.

**Comment by somebee** [comment]
Even though SSR (server-side rendering) is not really well-tested on v2 yet, it should already be possible to have a server that renders the exact same thing as the client. At scrimba.com we return all pages from the server as well as rendering on the client, using the same code. As for dynamic content that is syncronoushly loaded it would make sense to allow compiling to html for sure!

**Comment by scanf** [comment]
It's possible but wouldn't it be cool if the tooling also supported building tags to HTML pages? This would be sweet when making one off sites / landing pages.
