### ISSUE TITLE
shortcut for var(--variable-name)

### ISSUE THREAD

**Issue by ericvida** [imba/imba#371]
Do we need to use `var()`? a shorthand would be nice.
Couldn't the compiler be programmed to tell the difference between a declaration`--var:red` and an instance`color: --var`?

**Comment by somebee** [comment]
Currently you can use `$varname` inside styles as a shorthand, both for setting and including.

```imba
css button $size:20 width:$size
```

But I'm still not 100% it won't be removed. Might instead just autowrap `--var` as values inside `var()` as you suggested. Is that good enough?

**Comment by ericvida** [comment]
hmm. 
`$` is familiar from preprocessors, but I think `--var` is a smaller change from the css syntax.

**Comment by somebee** [comment]
After using it for a while, do you think we should stick with `--var` or allow `$var` syntax? If we just use `--var` it feels a little more hacky to autowrap them whenever they are not inside a `var()`.

**Comment by Bohooslav** [comment]
After using CSS variables it is more natural for me to use `--var` than `$var`

**Comment by ericvida** [comment]
I can get used to $var
but I do like `--var` better. I just want to instantiate it without `var()`
like `ff:--font`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
