### ISSUE TITLE
border aliases missing

### ISSUE THREAD

**Issue by ericvida** [imba/imba#374]
Any particular reason why these are missing?

`b: red5 5px solid` - border:
`bb: red5 5px solid` - border-bottom
`bt:  red5 5px solid` - border-top
`bl: red5 5px solid` - border-left
`br: red5 5px solid` - border-right

**Comment by somebee** [comment]
The main reasons was that `b` collides with `bottom` alias, and that `br` could also be `border-radius`. But from experience I've felt that we need to add them again. What do you think of the latest iteration? https://v2.imba.io/manual/styling/aliases. The idea is that all border aliases start with `bd`, and all radius aliases start with `br`.

**Comment by somebee** [comment]
Correct, all radius aliases only starts with b. Not sure about that.

| Name | Description |
| --- | --- |
| br | border-radius |
| btlr | border-top-left-radius |
| btrr | border-top-right-radius |
| bblr | border-bottom-left-radius |
| bbrr | border-bottom-right-radius |
| btr | top-left + top-right |
| bbr | bottom-left + bottom-right |
| blr | top-left + bottom-left |
| brr | top-right + bottom-right |

**Comment by somebee** [comment]
As a consequence of moving border aliases into `bd` prefix, we can also use `bs` for `box-shadow`. I think it feels pretty consistent with `bg:gray2 br:2px bs:glow` - same length for all these common shorthands, and everything starting with `b` is related to appearance of the box.

**Comment by ericvida** [comment]
I know you're following the css names, but i think as an alias. it's more consistent to do always "br"
brtl
brtr
brbl
brbr
brt
brb
brl
brr

or what if you used `rd` for radius instead of `br`

rdt - top
rdb - bottom
rdl - left
rdr - right
rdtl - top left
rdtr - top right
rdbl - bottom left
rdbr - bottom right
etc...

**Comment by somebee** [comment]
I like that idea. Do you prefer `rd` or `br`? And is the `bd` prefix for border okay?

**Comment by ericvida** [comment]
man, there's a lot of b's. 
If we move t,r,b,l to the end it makes for better aliases and less conflict.
if we move box shadow to `bxs`, we can predictably use `bs` for border-style.
```
bw t    = border-top-width
bw r    = border-right-width
bw b    = border-bottom-width
bw l    = border-left-width

bs      = border-style
bs t    = border-top-style
bs r    = border-right-style
bs b    = border-bottom-style
bs l    = border-left-style

b      = border
b t    = border-top
b r    = border-right
b b    = border-bottom
b l    = border-left
b w    = border-width
b sp   = border-[sp]acing
b co   = border-[co]llapse

bc      = border-color
bc t    = border-top-color
bc r    = border-right-color
bc b    = border-bottom-color
bc l    = border-left-color

bi      = border-image
bi o    = border-image-outset
bi r    = border-image-repeat
bi s    = border-image-source
bi sl   = border-image-slice
bi w    = border-image-width

br      = border-radius
br tr   = border-top-right-radius
br tl   = border-top-left-radius
br br   = border-bottom-right-radius
br bl   = border-bottom-left-radius
br l    = brtl, brbl
br r    = brtr, brbr

bxdb    = box-decoration-break
bxs     = box-shadow
bxsi    = box-sizing

bka     = break-after
bkb     = break-before
bki     = break-inside
```

**Comment by ericvida** [comment]
The spaces in the aliases are just for show

**Comment by ericvida** [comment]
i like rd m but i think it makes more sense with br

**Comment by ericvida** [comment]
@somebee

**Comment by somebee** [comment]
I updated your comment to move border-width to `bw` instead of `bdw`, since I guess it was just an oversight :)

**Comment by eulores** [comment]
I like `rd` for border-radius. The only radius in CSS refers to `border-radius`, so no need to include the border prefix, IMO.
There's also a certain logic to it: `bd` for bor-der, and `rd` for ra-dius, and both are followed by cardinal directions.
We will just get used to it, no matter what will be decided in the end.

**Comment by somebee** [comment]
I'll be updating this in the next alpha (in a few hours). Don't have a system in place for deprecations etc just yet, and since we're still in alpha I'll just brutally change them :P So if you are using them in your project now you might need to search around and update.

Will also push new version of vscode plugin to fix autocompletion for them etc.

**Comment by somebee** [comment]
So, these will be the new border-related aliases:
```
# border
bd: 'border'
bdr: 'border-right'
bdl: 'border-left'
bdt: 'border-top'
bdb: 'border-bottom'

# border-style
bs: 'border-style'
bsr: 'border-right-style'
bsl: 'border-left-style'
bst: 'border-top-style'
bsb: 'border-bottom-style'

# border-width
bw: 'border-width'
bwr: 'border-right-width'
bwl: 'border-left-width'
bwt: 'border-top-width'
bwb: 'border-bottom-width'

# border-color
bc: 'border-color'
bcr: 'border-right-color'
bcl: 'border-left-color'
bct: 'border-top-color'
bcb: 'border-bottom-color'

# border-radius
rd: 'border-radius'
rdtl: 'border-top-left-radius'
rdtr: 'border-top-right-radius'
rdbl: 'border-bottom-left-radius'
rdbr: 'border-bottom-right-radius'
rdt: ['rdtl','rdtr']
rdb: ['rdbl','rdbr']
rdl: ['rdtl','rdbl']
rdr: ['rdtr','rdbr']
```
Won't rush to add border-image aliases etc just yet.
