### ISSUE TITLE
Shadow Bug + Styles Feature Idea (Depth property)

### ISSUE THREAD

**Issue by ericvida** [imba/imba#375]
I was trying to combine shadow sm/md/lg values with a custom value, but I could not.
This is not working for me.
```imba
shadow:lg, 0px 5px blue9
```
 
My goal was to create a button with depth as shown below, combined with `shadow:lg` drop-shadow effect.

![CleanShot 2020-06-23 at 12 49 31](https://user-images.githubusercontent.com/13579055/85431799-e1d64980-b536-11ea-8f30-066f460a6d3a.gif)

The above button effect is created as follows:
```imba
css button
	bg:purple7 @hover:purple6 @active:purple7
	shadow: 0px 5px purple9 @hover: 0px 6px purple8 @active: 0px 3px purple9
	transform: translateY(-5px) @hover:translateY(-6px) @active: translateY(-3px)
```
The problem is that I cannot use it in combination with the `sm, md, xl` values. I'd have to define each shadow layer manually from scratch.

## Request
I was wondering if it's possible to allow adding to the shadow pre-defined values with a comma. `shadow:sm, 0 5px blue7`
or even combine them `shadow: sm,xl`

## Alternative Depth Syntax
Alternatively or additionally, I thought there could be a syntax for creating depth.
```imba
css button
	depth: 5px purple9 @hover 6px purple8 @active 3px purple9
```
would be short for this:
```imba
css button
	shadow: 0px 5px purple9 @hover: 0px 6px purple8 @active: 0px 3px purple9
	transform: translateY(-5px) @hover:translateY(-6px) @active: translateY(-3px)
```
It'd be great if it could combine with any other shadow property, so that they don't negate each other.
```
css button
	shadow: md
	depth: 5px purple9
```
So the above, would essentially be the same as doing this:
```
css button
	shadow: 0 5px purple9, 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
	transform: translateY(-5px)
```
### Alternate syntax for depth
Another syntax possibility would be: If there is a single pixel value, it would be interpreted as depth.

```imba
css button
	shadow: 5px purple9 @hover: 6px purple7 @active: 0px purple9
```
same as
```
css button
	shadow: 0px 5px purple9 @hover: 0px 6px purple8 @active: 0px 3px purple9
	transform: translateY(-5px) @hover:translateY(-6px) @active: translateY(-3px)
```

Let me know what you think?

**Comment by somebee** [comment]
Some things are difficult to do while we try to work within the possibilities of regular css (we don't want to rewrite style rules live etc. But, multiple shadows, including custom shadows, should work in latest alpha now. See https://v2.imba.io/guides/handbook/styling/presets box-shadow section :)

**Comment by ericvida** [comment]
Wonderful. This should be enough.
