### ISSUE TITLE
Styles: Shadow color

### ISSUE THREAD

**Issue by ericvida** [imba/imba#380]
It'd be nice to color shadows.
I wonder if passing a color could work something like this.
```imba
shadow: sm teal5
```
Colored shadow:
![image](https://user-images.githubusercontent.com/13579055/85862966-51d31280-b777-11ea-8a68-6433f237f821.png)

Non-colored shadow:
![image](https://user-images.githubusercontent.com/13579055/85863080-7dee9380-b777-11ea-926e-0071a4b14588.png)

**Comment by somebee** [comment]
I'll think about how we could support that :)
