### ISSUE TITLE
BUG - Styles: Can't select svg from scoped styles.

### ISSUE THREAD

**Issue by ericvida** [imba/imba#386]
Scoped Styles selectors won't select an svg element.

```imba
css %themap
	fill: red # this works
tag Map
	css %themap
		fill: blue # this doesn't work
	def render
		<self>
			<svg [fill:purple] %themap> # inline style works
				<g>
					<path>
					<path>

```
I tried using svg, `%map`, `.map` and `#map to select the svg, and they all have the same result for me.

alpha.68

**Comment by somebee** [comment]
Will look into this now. Thanks for reporting :)

**Comment by somebee** [comment]
There is a quickfix but I'm improving some parts of how scoped classes are set at the same time, to also allow for file-scoped css and a general cleanup. Btw, after adding scoped classes that even work with inheritance I'm downplaying the mixin concept for now -- might not be something we end up needing or wanting.

**Comment by somebee** [comment]
This should be working now.
