### ISSUE TITLE
BUG: `.catch` error.

### ISSUE THREAD

**Issue by ericvida** [imba/imba#388]
Not sure, but I think catch is not working as it should. Maybe my syntax is off.
```
tag app-root
	...
	def mount	
		catchFetch!
			.then do(response) console.log "Yay!"
			.catch do(error) console.log error
```
![image](https://user-images.githubusercontent.com/13579055/87203346-41628200-c2b7-11ea-8661-6a1c7ddb6e75.png)

**Comment by somebee** [comment]
Yeah, that's some parsing issue. In the meantime I would do

```imba
try
	await catchFetch!
	console.log 'yay'
catch e
	console.log e
```
