### ISSUE TITLE
Specify timezone for Bi-Weekly Imba Community Meeting.

### ISSUE THREAD

**Issue by drumrock** [imba/imba#392]
"Bi-Weekly Imba Community Meeting" is at (3PM/9AM for example), and it's probably Oslo timezone.

Would be easier to make plans for attending if it will be specified like "3PM, GMT+x" or "Our timezone is GMT+x, so if you live somewhere else, check what your time will be" in:

- https://github.com/imba/imba (section Community)
- (meeting notes) https://docs.google.com/document/d/1ABGjOJut9eXrajYjdN4G4-UGGU4gvKznLk5CAaXYjso/

**Comment by scanf** [comment]
Please use our Meetup page for this kind of information, [Imba Oslo Meetup](https://www.meetup.com/Imba-Oslo-Meetup).

Thanks for the feedback @drumrock 🙏
