### ISSUE TITLE
Font not changing when using ternary statement in the style blocks

### ISSUE THREAD

**Issue by aalemayhu** [imba/imba#399]
Hei,

tried using a ternary operator to change the font size to XL, was using the docs as a guide. https://v2.imba.io/manual/styles/theming/typography

It does not work as expected, see the screenshot and code below. You easily reproduce the issue by trying to click on the heading and the text is supposed to get the font-size `64px` which it does not.

```imba
tag x-app
	prop time = new Date()
	
	def render
		<self [d:flex flw:wrap]>
			<h1[fs: {time.toString!.includes('Imba') ? 6xl : xl}] @click=(time = 'Imba time!')> "The time is {time.toString()}"

imba.mount <x-app>
```

## Actual

As you can see the in the image the text is simply not changing 

<img width="1276" alt="Skjermbilde 2020-08-08 kl  13 43 45" src="https://user-images.githubusercontent.com/925044/89709147-95778980-d97d-11ea-9ebd-3c03b724615a.png">

## Expected

<img width="848" alt="Skjermbilde 2020-08-08 kl  13 43 59" src="https://user-images.githubusercontent.com/925044/89709155-a3c5a580-d97d-11ea-974f-38546c96b2f7.png">

**Comment by scanf** [comment]
I see, so should I close this then? We can still just use integers and it works fine in that case with `px`.
