### ISSUE TITLE
Simplify FOR loops

### ISSUE THREAD

**Issue by eulores** [imba/imba#407]
### Description

Today, Imba has **three `for` loops**, inherited from Imbav1 and from Javascript.

- for in
- for of
- for own of

I want to propose a **single `for` loop**, with comfortable access to most **loop properties** using `getter` methods.
This proposal is heavily inspired by [Jinja](https://jinja.palletsprojects.com/en/2.11.x/templates/#for).

#### Syntax

```js
for obj in anything
  // do something with obj
  console.log obj.key, obj.value
  console.log "{obj} == {obj.key}"

// loop through all properties, also inherited ones, up to parentObject
for obj in anyObject, parentObject
  // do something with obj

// different syntax, same purpose
for obj in anyObject .. parentObject
  // do something with obj
```

The for loop can be applied to anything with either a length property or an iterator.

#### Properties

`obj.index` zero based (0 onwards)
`obj.index1` one based (1 onwards)
`obj.first?`
`obj.last?`
`obj.even?` second element is even
`obj.odd?` first element is odd
`obj.cycle('red', 'green', 'blue')` cycles through all arguments and restarts once exhausted
`obj.revindex` zero based (starts at length-1 and ends at 0)
`obj.revindex1` one based (starts at length and ends at 1)
`obj.key`
`obj.value` defined for maps and objects. If `undefined`, defaults to `obj.key`
`obj` on its own acts like `obj.key`

#### Looping over ...

- `Array`
Iterate over all values of the array. `key` and `value` are the same and point to each element.
- `Set`
Iterate over all values of the set. `key` and `value` are the same and point to each element.
- `String`
Iterate over all characters of the string. `key` and `value` are the same and point to each character.
- `Iterator`
Returns one element after another, until the iterator is exhausted. `key` and `value` are the same. Since there is no length associated with the iterator, all properties of obj requiring length return `undefined`
- `Map`
Iterates over all pairs of the map. The return is mapped onto `key` and `value` properties.
- `Object`
Iterates over all pairs of the map. The return is mapped onto `key` and `value` properties. The optional `parentObject` extends the looping with inherited properties, all the way up to `parentObject`. If set to `true`, then all properties from the complete prototype chain are fetched.

### Why

Newcomers might feel overwhelmed by all the different for loops. The default should just do what is expected. Still, supporting more advanced use cases (looping through properties inherited from the prototype chain)

Other languages (Python) have simpler for loops, that still support all possible use cases.

### Possible Implementation & Open Questions

- getter methods?
- proxy object?
- computed properties?

Even without the loop properties, a **simplification is desirable**. And now, before Imba goes to beta, might be the right moment.

### Is this something you're interested in working on?

No. I do not have the necessary skills.

**Comment by daarxwalker** [comment]
Sounds good for me, good example is Go, there only one loop with few patterns, like i = 0; i < length; i++ and for i, item := range slice. In JS it's little bit mess with loops, but Imba should be rly simple. I think, there could be some kind array validator, use this loop or another for object, but in Imba syntax should be only one. What do you think? @somebee

**Comment by somebee** [comment]
I can cross-post here, as the discussion belongs here I guess.

As we've discussed previously, I do agree that going for a single way to iterate would be ideal, but the more I've dug into the performance implications etc I see it as pretty unlikely. for in is heaps faster than native es6 iterators and will likely stay that way for a very long time, since es6 iterators are doing a lot more.

If we forget for own of for a while, I don't think it's that problematic to have two loops - for in being the choice for array-like lists and for of for objects and everything else.

**Comment by somebee** [comment]
I do like the idea of using an object though - so that we can get all these other features. Would need some compilation magic to detect the features used in a loop and only calculate what is needed.
