### ISSUE TITLE
Aliases for justify + align combination

### ISSUE THREAD

**Issue by somebee** [imba/imba#408]
```
ja: justify & align
jai: justify-items & align-items # replaces pi for place-items
jac: justify-content & align-content # replaces pa for place-content
jas: justify-self & align-self  # replaces ps for place-self
```

See https://css-tricks.com/snippets/css/complete-guide-grid/#prop-justify-items for an intro to these properties. They are extremely useful / common when dealing with both flexboxes and grids. I see muself repeating `j:center a:center` all the time.

This proposal would remove the `place-*` aliases `pi,pc,ps`. They could at first glance be confused for padding aliases since they start with `p`, so I think this is a cleaner alternative. Any input?

**Comment by daarxwalker** [comment]
@somebee 
Just tried place-content (pc) and it's not working :D not compile, result prop stays as pc: center for example

**Comment by daarxwalker** [comment]
Ah, I see. Cool. I was confused, cs VSC plugin doesn't know, maybe outdated.
