### ISSUE TITLE
CSS-in-Imba

### ISSUE THREAD

**Issue by daarxwalker** [imba/imba#414]
### Description

Using props and variables in css.
Like CSS-in-JS, but better. 
There are two ways for me, or maybe more. When some part of css have prop or variable: 
1. ... render style to head with this code (only this part, split css to two parts)
2. ... create modifier by name of prop and value maybe, or something like this

### Why

Instead of creating lot of modifiers or custom atomic styles, it will be easier to write styles something like this.
It's not filled gap. I think, would be really cool to have such feature.

### Possible Implementation & Open Questions

```
tag Custom
    prop color = 'blue'

    css &
        c: {color}

```

### Is this something you're interested in working on?

Yes

**Comment by trafnar** [comment]
Another reason for this is that if you like to write css with one rule per line, it's not convenient to do for inline styles.

So, if you like writing:
```imba
css
  .foo
    w:10px
    h:10px
```

to do it with dynamic values you have to write in one line:

```imba
<div[w:{width}px h:{height}px]>
```

or, do something like this, which really makes your HTML ugly:

```imba
<div
  [w:{width}px]
  [h:{height}px]
>
```
