### ISSUE TITLE
bs -> box-shadow alias is not working

### ISSUE THREAD

**Issue by aalemayhu** [imba/imba#421]
I was debugging some box shadow issues on the new Scrimba site but could not figure out why the styles were not being applied. I think Eric has also reported this on Discord IIRC.

**Comment by eulores** [comment]
Try bxs

https://github.com/imba/imba/blob/abd905f2ca0a871422c5aeec75e7b69180708264/src/compiler/styler.imba#L221

**Comment by scanf** [comment]
@eulores could you update v2 documentation? Thanks 🙏

**Comment by eulores** [comment]
Had a first look at the documentation generation. Didn't understand anything at all!!
But found two things that might be helpful:
- Old reference to `bs` should be changed to `bxs`, around line 3515 of `content/manual.md`
`<doc-style-aliases data-regex='---' data-include='bs,opacity,pe,zi,prefix,suffix,us'></doc-style-transform-aliases>`
- Imba is still at version 77. Should be updated to 89. I won't do it as I don't know if this is a breaking change.
- My guess: expansion of the aliases is done by the Imba compiler `imba/src/compiler/styler.imba`. Not sure...

Will try to set up a development environment to generate docs locally, but quite a challenge under Windows ;-)

**Comment by scanf** [comment]
We believe in you, you can get it running windows 💪 

Thanks for elaborating.
