### ISSUE TITLE
Provide ZSH and BASH auto completion files

### ISSUE THREAD

**Issue by aalemayhu** [imba/imba#423]
I use `imbac` several times per day and it's really painful to have to manually type out some of these commands and the file system paths. This is a solved problem and we can easily adress it by providing users with proper shell autocompletion files.

https://iridakos.com/programming/2018/03/01/bash-programmable-completion-tutorial

[https://mrigank11.github.io/2018/03/zsh-auto-completion/](https://mrigank11.github.io/2018/03/zsh-auto-completion/)

**Comment by somebee** [comment]
Are you up for that?
