### ISSUE TITLE
New predeclared font-sizes

### ISSUE THREAD

**Issue by somebee** [imba/imba#428]
The `3xl` syntax interferes a little with dimensions / numbers with units, and does not feel too clean imho. It is also definitely possible to just use concrete font sizes instead of any of these aliases, but I've grown to like them, and think that designing becomes easier when we deliberately constrain ourselves with these types of presets. Same goes for box shadows and border radius etc.

Let's keep the `sm- md- lg-` variants out of the discussion - they are a separate issue/discussion.

So, to cover more ground I'm proposing another size alias, `hg` for huge. Then we have `sm md lg xl hg`.  There are some potential variations here. The current proposal I'm liking the most is:

```
xxs 10px
xs  12px
sm  14px
md  16px
lg  18px
xl  20px
xxl 24px
xxxl 30px
hg 36px
xh 48px
xxh 64px
xxxh 96px
```

For reference, here is the current scale:

```
xxs 10px
xs  12px
sm  14px
md  16px
lg  18px
xl  20px
2xl 24px
3xl 30px
4xl 36px
5xl 48px
6xl 64px
```

What are your thoughts?

**Comment by ericvida** [comment]
>The `3xl` syntax interferes a little with dimensions / numbers with units, and does not feel too clean imho. It is also definitely possible to just use concrete font sizes instead of any of these aliases, but I've grown to like them, and think that designing becomes easier when we deliberately constrain ourselves with these types of presets. Same goes for box shadows and border radius etc. ...

@somebee
one idea:
sxx
sx
sm
md
lg
lx
lxx
lxxx
hg
hx
hxx
hxxx

or (as I'd prefer):
1
2
3
4
5
6
7
8
9
10
11
12

or:
10 mn (minimum, mini)
12 tn (tiny)
14 sm
16 md
18 lg
20 xl
24 xxl
30 xxxl
36 hg
48 xh
64 xxh
96 mx (maximum, max)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ericvida** [comment]
just ideas

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eulores** [comment]
Keep in mind that not everybody is using vscode for the incr/decr actions.
I prefer a numeric scale, maybe with a prefix/suffix so as not to confuse them with pixels.
Whatever you choose as a nomenclature, you will be limited by its bounds (tn, sm, ..., gg has 6 elements only). And font sizes are per nature limitless.
> Imba allows unitless numeric values for all sizing related properties. For margin, padding, sizes, and positions unitless numbers are equal to 0.25rem * number. 1rem is 16px by default, so this means that the scale increments by 4px for every integer.

I would use a similar scaling also for font size, and then map tokens from your preferred scale to the most used sizes.

**Comment by eulores** [comment]
If you use a custom linear scale, then base it on rem, not pixels.
I would then publicise the presets (to push towards consistency), but still leaving the linear scale available in case presets are not enough (without falling back on pixel counting).

BTW, I do agree with your reasoning!

**Comment by eulores** [comment]
Any way of allowing user-defined custom font sizes? I know it's a silly question...

**Comment by eulores** [comment]
Please allow an alternative for all options configurable in `imbaconfig.json`.

For speed reasons, would like to configure the Imba compiler without having to resort to writing `imbaconfig.json` to disk first!
