### ISSUE TITLE
Are there  any limitations in using JS libraries like jquery, isotope etc with Imba like React?  

### ISSUE THREAD

**Issue by kmabadshah** [imba/imba#436]
Will there be any limitations in using JS libraries like jquery with Imba? In react, people are often recommended not to mutate the dom directly. Is that a problem with imba if I change the dom directly with jquery? I'm a newbie with Imba so any suggestions are aprreciated, thanks .

**Comment by trafnar** [comment]
I'm not sure whether mutating the dom directly would cause problems (it probably could work) but generally if you find yourself using jQuery it's because you don't understand how to do the same task using Imba. You should ensure that there's not a better "imba way" to do what you are attempting (same goes for react etc).

If you share a scenario of something you are trying to accomplish, I'll help you see how to do it with Imba.

**Comment by kmabadshah** [comment]
@trafnar How about plugins? If I wanted to do everything the 'imba way' then I guess I'll have to rewrite the plugins myself. That doesn't sound very cool. What are your thoughts about plugins?

**Comment by trafnar** [comment]
Yeah, that's a good point, large existing code may be one of the main reasons to want to use jQuery within Imba. I wonder though, what types of plugins would you be interested in using? Perhaps their functionality is easy to recreate with Imba.

**Comment by kmabadshah** [comment]
@trafnar Isotope.js for example. It's an image filtering and sorting library. Just by looking at how it works, it seems pretty complex to re implement all by myself. Are there any alternatives to isotopejs built natively on imba?

**Comment by kmabadshah** [comment]
Is it possible to exclude some parts of the page from the imba ecosystem and use jquery stuff on those parts? On react, there are various ways to exclude parts of the application from the react ecosystem, that is, react will not update those parts of the page and let jquery do it's own thing. I've used that technique and it works fine. Is that possible with imba? Or does everything have to go through imba as a mandatory process?

**Comment by trafnar** [comment]
I'm not actually sure about using imba in parts of you page, but I assume that it's possible.

In terms of using isotope, looks like it exists as vanilla JS in addition to jquery plugin, I feel like that would probably work without much issue.

**Comment by kmabadshah** [comment]
My point is, whether you're using jquery plugins to manipulate the dom or directly manipulating the dom using the same plugin but with the vanilla js version, you're still 'manipulating the dom by yourself'. If one can manipulate the dom with vanilla Js, then what is the issue in using jquery for that purpose?

**Comment by trafnar** [comment]
Yeah, it probably works. Just seems a little less desirable to use jquery and I’m a together but I suspect it works. I’ll try an experiment when I have a moment

**Comment by trafnar** [comment]
Ok, I tried it out. I couldn't get jQuery to work but I'm not sure why, I was getting some weird errors. I think there must be a way to do it.

Isotope did work however, I imported the NPM module and it worked very easily. I used this code:

```
import Isotope from 'isotope-layout'

export tag App

	def mount
		var iso = new Isotope($grid, {
			itemSelector: 'div', layoutMode: 'fitRows'
		})

	css
		.box w:100px h:100px bgc:red m:10px
		.wide w:400px

	<self>
		<div$grid.grid>
			for item, i in [0 .. 100]
				<div.box.wide=(i % 10 == 0)
```

**Comment by kmabadshah** [comment]
Does the imba team say anything like "manipulating the dom directly is a bad practice and you should avoid doing it" ? I can obviously see that it can be done but are there any side effects noted in the imba docs for doing so?
