### ISSUE TITLE
Third argument for length in `for in`

### ISSUE THREAD

**Issue by somebee** [imba/imba#441]
An easy thing we could choose to support is an optional third argument to `for item in ` loops that will contain the total length of the loop.

```imba
let array = [1, 2, 3, 4]

for item in array
	yes
# index is optional second param 
for item,i in array
	yes
# length could be optional third param?
for item,i,len in array
	yes
	
```

It's not important, but I do find myself accessing the length in quite a few scenarios where I need to check if we are at the last index etc. Especially when the array is not a variable, this often becomes clunky (and slow).

```imba
let arr = view.filtered!
for item,i in arr
	if i == (arr.length - 1)
		# do something		
```

With the optional third arg it would be

```imba
for item,i,len in view.filtered!
	if i == (len - 1)
		# do something
```

Any opinions?

**Comment by eulores** [comment]
Yes, check the list of properties mentioned in ticket #407. They are used in jinja templates. I find them rather useful!

**Comment by somebee** [comment]
Nice. As we've discussed previously, I do agree that going for a single way to iterate would be ideal, but the more I've dug into the performance implications etc I see it as pretty unlikely. `for in` is heaps faster than native es6 iterators and will likely stay that way for a very long time, since es6 iterators are doing a lot more.

If we forget `for own of` for a while, I don't think it's *that* problematic to have two loops - `for in` being the choice for array-like lists and `for of` for objects and everything else.

**Comment by somebee** [comment]
After reading #407 again - if we could only have 3 parameters, might it make more sense to have the third one be the reversed index, rather than the length? length could clearly be calculated with `i + ri` and I find myself needing the reverse index much more often than the actual length, ref my example above.

**Comment by eulores** [comment]
Yes, indeed. Having a reverse index as well would help in many situations.

I do understand that for..in and for..of stay separate for performance reasons. That's ok.

Only bits to rescue from #407 are the loop index related properties, but many are superfluous. No need for base-1 indices!

If index+rindex==length, then world is round 😂
