### ISSUE TITLE
css reset when / how to include

### ISSUE THREAD

**Issue by somebee** [imba/imba#443]
I usually include the preflight css reset from Tailwind because it truly resets everything. no margins or styling for headings or anything else. I see that we probably shouldn't incude that by default but it clearly makes sense to do a good reset.

Should it be possible to reset stuff inside a scope only? Like `css reset:preflight` in a file to reset css for all file-scoped elements, or component scoped etc? If you're working on a component that is to be included in an existing application etc that might make sense.

Any proposals for css reset syntax? Or should we just ask people to bring their own resets? That will make the 'design system' much less consistent than in tailwind.

**Comment by eulores** [comment]
Yes, wait! I was struggling with the reset code while implementing hot restyling (part of esimba). Will dive into this topic beginning next week when I'll have more time, and come up with suggestions...

**Comment by ericvida** [comment]
> I usually include the preflight css reset from Tailwind because it truly resets everything. no margins or styling for headings or anything else. I see that we probably shouldn't incude that by default but it clearly makes sense to do a good reset.
> 
> Should it be possible to reset stuff inside a scope only? Like `css reset:preflight` in a file to reset css for all file-scoped elements, or component scoped etc? If you're working on a component that is to be included in an existing application etc that might make sense.
> 
> Any proposals for css reset syntax? Or should we just ask people to bring their own resets? That will make the 'design system' much less consistent than in tailwind.

I had a proposal for reset syntax here: https://github.com/imba/imba/issues/372
