### ISSUE TITLE
Add event modifier that combines stop and prevent

### ISSUE THREAD

**Issue by somebee** [imba/imba#446]
I often find myself declaring event handlers with both `stop` and `prevent` modifiers. Stop ensures that the event wont continue bubbling up the dom tree, while prevent prevents native behaviour (like submitting a form etc).

Could we come up with a single modifier that combines the two? Suggestions?

**Comment by eulores** [comment]
disable? isolate?

**Comment by eulores** [comment]
**solo** in the sense of having no interaction with the surrounding environment. Also only 4 letters, easier to type than **isolate**
