### ISSUE TITLE
Disallow multiple declarations on single line

### ISSUE THREAD

**Issue by somebee** [imba/imba#459]
The pattern `let a = 1, b = 2, c = 3` is source to a lot of ambiguity in the language because arguments are also comma-separated, we can call methods without parens, and declarations can act like expressions. Just look at the three expression:

```imba
let x = new Array a,b
let y = 10, z = 20 if test
imba.mount(let app = <App>, outerElement)
```

Looking through our own codebases on scrimba we're actually _never_ using comma-separated declarations - and not because it isn't currently supported, but because it seldom feels like good practice.

With the new approach, `let/const` will behave much more consistently and simplify a lot of things. Do anyone have strong opinions against this, please shout out now :)

If you really, really want to keep them on one line you can do `let [a,b,c] = [1,2,3]` or predeclare with `let [a,b,c] = []`. We can also support `let a = 2, let b = 3` if the need arises.

**Comment by trafnar** [comment]
Sounds good to me, I was never a big fan of those comma separated declarations
