### ISSUE TITLE
Snowpack(imports) doesn't seem to work with v2

### ISSUE THREAD

**Issue by illogikal** [imba/imba#475]
I attempted to use parcel with imba v2 and it didn't seem to work. I am now trying with snowpack, and imports from within an imba file don't seem to work. I used the imba snowpack template. tippy.js for example doesn't work as a normal import, and i ended up having to import it via unpkg. Do normal imports work within imba via snowpack? I am on the latest version of snowpack (2.17.1) since the earlier versions also didn't seem to allow importing css within css files. Can someone share their experience of snowpack with imba? I don't mind contributing to docs to help out.

**Comment by illogikal** [comment]
It's not the latest commits in the repo then? If not I'll wait.

**Comment by illogikal** [comment]
I have hacked it into working with the snowpack template by removing the imba-snowpack plugin, and changing the package.json like so. I want to import sugar.js within an imba file but it's giving me a weird error. I guess the import is not working properly? I am importing this file https://sugarjs.com/download/ with everything selected into my root imba file and it gives me an error. 
``` package.json
  "scripts": {
    "start": "./node_modules/imba/bin/imbabuild ./src/app-root.imba -o ./src/app-root.js && npx snowpack dev",
    "build": "./node_modules/imba/bin/imbabuild ./src/app-root.imba -o ./src/app-root.js && npx snowpack build",
    "dev": "./node_modules/imba/bin/imbabuild ./src/app-root.imba -o ./src/app-root.js && npx snowpack dev"
  },
```
``` imbaconfig.json
{
	"entries": {
		"./src/app-root.imba": {
			"file": "./dist/index.js",
			"platform": "browser",
			"format": "esm"
		}
	},
	"theme": {
		"fonts": {
			"mono": ["Source Code Pro", "Consolas", "Menlo", "Monaco", "Courier", "monospace"]
		}
	},
	"serve": {"port": 10004}
}
```

**Comment by andregoldstein** [comment]
Closing this for now as Imba v2 is moving very strongly in the direction of the integrated builder. Feel free to reopen if required.
