### ISSUE TITLE
Safe operator get on objects

### ISSUE THREAD

**Issue by illogikal** [imba/imba#476]
I am not aware if this is in the pipeline or not, but an operator that can deep get keys and safely return null if the subkey is not found might be useful?

**Comment by eulores** [comment]
Are you aware of the double dot operator?
father..son..sister

I couldn't find it in the documentation (not yet)

**Comment by illogikal** [comment]
I'm not sure, but if I have a json like {one: {two:{three: 'four}}} and I want to try to access the key 'one.two.three.five' it returns null instead of error. I'm aware of many ways to do this in js, but I'm wondering if there's an imba way. 

https://github.com/chetverikov/opath

I really like how this library addresses object getting and setting with the path strings.

**Comment by illogikal** [comment]
Oh I haven’t heard of this operator before.will give it a try
