### ISSUE TITLE
Imba router doesn't seem to work with default '/' route with latest version

### ISSUE THREAD

**Issue by illogikal** [imba/imba#477]
I'm using the latest esbuild branch, and I have imported imba router, the default route always shows whichever other route is active:

```i
mport 'imba/router'
import { Stores } 	from './stores/Store'
import { User } 	from './lib/User'
import {Button} 	from './components/Button'
import {Header} 	from './tags/Header'
import {Footer} 	from './tags/Footer'
import {Body} 		from './tags/Body'
import {Config} 	from './tags/Config'

import {Home} 		from './pages/Home'
import {About} 		from './pages/About'
 
tag app-root
	prop store
	def render
		<self%app>
			<Config>
			<Header store=store>
			<Body>
				<Home store=store route='/'> # always showstemp1.location.url.pathname
				<Home store=store route='/'>  if router.location.url.pathname == '/' # this works
				<About store=store route='/about'>
			<Footer store=store>

let store = new Stores()
imba.mount <app-root store=store>
```
Have updated with a temporary hack.
I see there is a Route class there. Is it possible to do it more like how react router does it? A route component makes more sense than shoving a route prop on any tags in the same file as the import.. I have been using imba for about a week now and I really like it, but the 'magicness' of some variables being accessed without declared could easily become overused and have a similar problem to ruby.

**Comment by illogikal** [comment]
It seems to work well apart from that bug I noticed. I have to say I really like what you've done with this project. 

There is this project https://hyperstack.org/, which has a ruby flavored version of react via opaljs. It's very similar to this, but given that it's opal. It's unfortunately very resource heavy serving and building. This actually hits the sweet spot between all the tradeoffs. Have you considered trying to make this a rails gem? I noticed some ruby repos in your account 👍

**Comment by illogikal** [comment]
I'm sure you're probably insanely busy what with leading the push of a whole framework into the world, but you should really give it a try. Pull their example app and try it out. The syntax is very very close to imba, but it's a good thing that you didn't use opal because unfortunately it's actually quite slow performance wise. Imba is actually weirdly fast, even compared to react just from a feel perspective. The only advantage it has over imba in my opinion since i've used it a lot is that it allows for hooking into the react ecosystem and so you get all of the work others have done there. In imba's case I also think this might end up being a good thing because imba's so much lighter weight, (and fast!). I am quite interested to see how I can contribute to the ecosystem, Maybe I can start making some imba modules. Would it be possible to post a minimal example of how to integrate the esbuild branch into a new product?

**Comment by qwars** [comment]
i use route="/*$"

**Comment by illogikal** [comment]
Would be good to document this...

**Comment by peter-wasilko** [comment]
I just started using qwars Dec 14, 2020 "/*$" solution to restrict content to an exact match of base URL. May I suggest the convention of using .exact on the route attribute as an implicit shortcut to preclude matching nested sub routes in general?
