### ISSUE TITLE
Router reload route="/page"

### ISSUE THREAD

**Issue by qwars** [imba/imba#483]
### Imba Version: 2.0.0-alpha.100

```
import 'imba/router'

let counter = 0

imba.mount <header>
	<a route-to="/"> "Main"
	<a route-to="/one-page"> "ONE-PAGE"
	<a route-to="/two-page"> "TWO-PAGE"
imba.mount <main>
	<em> "Counter: { ++counter }"
	<div route='/one-page'> "It one-page"
	<div route='/two-page'> "It two-page"
	<div route='/'> "It main-page"
imba.mount <footer>

```

It stopped working after clicking on links

[video.mp4.zip](https://github.com/imba/imba/files/5676549/video.mp4.zip)

**Comment by qwars** [comment]
< header > , < main > - not exists `autoschedule, isAwakened, isHydrated, isMounted, isMounting, isRender, isRendered, isRendering, isScheduled`

**Comment by Bohooslav** [comment]
Imba 2 has bad support of native tags. Please use web components.

**Comment by qwars** [comment]
Yes, you can, but I think it would be great to do this behavior too.

**Comment by qwars** [comment]
And we will learn the opportunity for an adequate simantika of the document, SEO will be grateful to us

**Comment by qwars** [comment]
Looked at all the code, you just need to add `render` for such elements

**Comment by qwars** [comment]
если по русски, там не слишком сложно сделать, на текущий момент такое положение заставит писать практически все тэги для HTML отдельно, или забыть что есть тэги HTM. Что за собой влечет потерю всего функционала браузеров по отношению к тегам ( встроенные стили, события и еще кучу всего ).

**Comment by qwars** [comment]
tag MyTag < details - This will just delete everything that has web components.

**Comment by qwars** [comment]
Previously, it was possible to take a ready-made layout and adapt it very quickly. Now writing everything from scratch.

**Comment by qwars** [comment]
And if you just add to document.body - autoschedule, isAwakened, isHydrated, isMounted, isMounting, isRender, isRendered, isRendering, isScheduled. I think everything will work

**Comment by Bohooslav** [comment]
- The least what I do is to wrap everything in a root component and place all the stuff inside. I don't see any problem in wrapping of the native tags in the web components. You still may and should use native tags but inside of components.
Your style is unusual. Go to any popular website that uses modern framework and you will see how the stuff is created. 

Yeah, lack of good support of native tags isn't neat but in the other hand it pushes you to change your code style in the best side.

In any way I would recommend you read more the docs and see example of others on scrimba.

**Comment by qwars** [comment]
Agree, if it works too, imba will be much better ...

**Comment by qwars** [comment]
Replacing web components in a ready-made version of html tags entails rewriting everything that works with these tags (CSS, Events, etc.)

**Comment by Bohooslav** [comment]
Rewriting is always painful, but it is with of it's time.

**Comment by qwars** [comment]
In general, if this does not happen. We'll have to stay on React. Although all the developers of my firm have already tried Imba1, AND agree to work with imba2. But they cannot and are forced to do everything in React. 
You don’t understand, these are not personal projects, Time was spent, Paid by the customer ... How can you wait within your personal world ...

**Comment by qwars** [comment]
You will have to create everything, completely everything ... And only because you have no desire to make such an opportunity, for simple HTML tags.  
Or it's easier to stop being an imba fan ...

**Comment by qwars** [comment]
I think there is no point in answering ...

**Comment by qwars** [comment]
![image](https://user-images.githubusercontent.com/1351453/102008773-d7ae3e80-3d54-11eb-8e73-d74bf2511af1.png)

**Comment by qwars** [comment]
![image](https://user-images.githubusercontent.com/1351453/102008808-0af0cd80-3d55-11eb-9df4-93b9e1d12dca.png)

**Comment by qwars** [comment]
![image](https://user-images.githubusercontent.com/1351453/102008944-e812e900-3d55-11eb-87fb-37676bd5b36e.png)

**Comment by qwars** [comment]
There are still many companies that only use IE.

**Comment by Bohooslav** [comment]
This is upsetting. I have no answer about what to do with existing projects but if you start a new one I would definitely use Imba 2.

**Comment by qwars** [comment]
I'm sure to use imba 2, even in the current state, only this is missing. The rest can be somehow circumvented, write your own. But if there is no way to fully use HTML tags (5), imba 2 loses its meaning and has no opportunity to advance in the web development market.

**Comment by qwars** [comment]
Все это хорошо работает, если сделать вот так
```
import 'imba/router'

let counter = 0

imba.mount do <header>
	<a route-to="/"> "Main"
	<a route-to="/one-page"> "ONE-PAGE"
	<a route-to="/two-page"> "TWO-PAGE"
imba.mount do <main>
	<em> "Counter: { ++counter }"
	<div route='/one-page'> "It one-page"
	<div route='/two-page'> "It two-page"
	<div route='/'> "It main-page"
imba.mount do <footer>
```

**Comment by qwars** [comment]
I figured it out, thank you all, now you can continue to research imba2

**Comment by qwars** [comment]
I figured it out, thank you all, now you can continue to research imba2

**Comment by Bohooslav** [comment]
I am glad for you. May you create the best apps.
