### ISSUE TITLE
Support `css` declarations inside render code

### ISSUE THREAD

**Issue by somebee** [imba/imba#490]
I often find myself needing to write css that are slightly too long / complex to add inline on elements, but for large tags I end up with a chaotic body of methods and css declarations. Could it be smart if we simply allow css declarations directly inside the render method? Like:

```imba
tag App
    <self>
        <header> "..."
        css div.test d:block
        <div> <span> "Hello"
```

I know it looks kind of messy in a small example like this, but the value of being able to keep styles as close as possible to the elements they are affecting shouldn't be understated. There wouldnt be any magic to it - they are treated as if they are defined in the tag declaration.

As a side-effect, this could also enable interpolated values in style rules (not just inline styles). Your thoughts?

**Comment by ericvida** [comment]
i would love to be able to nest styles like this.
```
<h1> "hello world"
    css c:teal5
    # or
    css & c:teal5
```
but you're wanting to still use css selectors right?


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ericvida** [comment]
I'm not against css in the render tag. I agree that would be easier to maintain.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by somebee** [comment]
Ooh, I actually like the idea of scoping the vas statements to their parent element. Then you could use it without a selector (like your example).

**Comment by ericvida** [comment]
Could it possibly be inline like this as well? `<h1> "hello world" css c:teal5`
Are you thinking of removing tag level css blocks? I think I still want them.
What will you use `[]` for if they're available? I'm curious. 

Maybe off topic, but can the keyword be `style` instead of `css`? I know it's longer, but I feel like css is just not accurate to what it can do.

**Comment by somebee** [comment]
Will still keep `[]` for truly inline styles. Enabled this in the latest alpha (113). Looking forward to try it in real apps and see how it feels. So far it feels really good actually. Also added action for folding/unfolding style blocks in the latest vscode-imba plugin, which helps even more.

![Kapture 2021-01-26 at 14 29 25](https://user-images.githubusercontent.com/8467/105851321-349f4480-5fe3-11eb-8273-03613bcecb94.gif)

Also added support for dynamic interpolation in these css rules - will try to document the new features this week.
