### ISSUE TITLE
Possible to two-way bind to custom form elements?

### ISSUE THREAD

**Issue by andregoldstein** [imba/imba#509]
### Description

Is it possible to have the convenience of the `bind` syntax when using a custom input component?

### Why

Use case, for example, is a checkbox input

Non working code:
```
tag checkbox-input
  prop value = false
  def render
    <label.checkbox> <slot>
      <input type="checkbox" bind=value>

...
<checkbox-input value=product.expired> "Expired?"
```

It's no biggie if not as can easily be made to work around with an emitted method

```
tag checkbox-input
  def render
    <label.checkbox> <slot>
      <input type="checkbox" @change.emit-toggle>

...
<checkbox-input value=product.expired @toggle=(product.expired = !product.expired)> "Expired?"
```

Or alternatively just keeping the "traditional approach"

```
<label.checkbox> "Expired?"
  <input type="checkbox" bind=product.expired>
```

**Comment by ericvida** [comment]
Try `<checkbox-input bind:value=product.expired> "Expired?"`
Maybe we need to document that.

**Comment by ericvida** [comment]
I tried your example, and it works for me.

**Comment by andregoldstein** [comment]
> Try `<checkbox-input bind:value=product.expired> "Expired?"`
> Maybe we need to document that.

Oh cool, that works, nice thanks!

**Comment by andregoldstein** [comment]
> I tried your example, and it works for me.

Hmm, will have to check again, pretty sure mine wasn't

**Comment by ericvida** [comment]
@andregoldstein I meant to say that I tried your example with the bind:value change.

**Comment by andregoldstein** [comment]
Closed as this seems to work as expected
