### ISSUE TITLE
Range operators

### ISSUE THREAD

**Issue by BigZaphod** [imba/imba#517]
Imba's range syntax as noted on the documentation page https://imba.io/language/control-flow indicates that using 2 dots is an inclusive range, and 3 dots is exclusive:

````
# from 0 up to (including) 3
for num in [0 .. 3]
	num
# [0,1,2,3]
````

and

````
# from 0 up to (excluding) 3
for num in [0 ... 3]
	num
# [0,1,2]
````

Most of Imba's syntax seems clean and clear to me, but this one is driving my a bit bonkers and I'm constantly getting it wrong.

Mentally, I keep thinking that the *inclusive* case should be the one with 3 dots because I keep thinking of it like, "okay, '..' means range, and '...' is like.. a one-longer range and therefore includes the end value."  Except that is exactly not how the language works!

I haven't done any significant research into this, but Swift is another language I'm quite familiar with, and in Swift the range operators are `...` and `..<`. This is likely leading to much of my confusion, because in Swift, `...` is in the inclusive/closed range. For example, `1 ... 3` means `[1, 2, 3]` and the `1 ..< 3` means `[1, 2]`.

My suggestion would be to reconsider the range operator so it's not so darned confusing - but it could just be me!

**Comment by jurajkapsz** [comment]
I never worked with ranges, and as I went through an exercise on ranges, I also think that the last argument should be included.

As a lay person, I consider a "range" to be simply as if I name out a set of values in real life, eg [`'Peter', 'Bill', 'John'`].
In an exercise on range, this feels counterintuitive to do:
```
for num in [0...3]
	console.log "Day {num + 1}"
```
I would write this by default this way:
```
for num in [1...3]
	console.log "Day {num}"
```
If I would need 3 indexes, I would do:
```
for index in [0...2]
	console.log "Index {index}"
```
If I would need indexes and counting, I would do:
```
for index in [0...2]
	console.log "{index + 1}: Index {index}"
```
If there is a `..` operator aswell, I would use that for leaving out the last range value, and `...` for having them all (`..` being "short by one").

My two cents.
