### ISSUE TITLE
Beta Launch List

### ISSUE THREAD

**Issue by trafnar** [imba/imba#519]
What would be required for us to confidently call Imba "Beta"

- [ ] Fix "phantom errors" in vscode (some related to imports, some related to comments)
- [ ] Fix object definition without `{` / `}` (causes errors in some cases)
- [ ] Remove/deprecate old vscode plugin
- [ ] Remove/deprecate old templates (webpack/rollup)
- [ ] Decide on and deprecate some syntax decisions (like `do |foo|` vs `do(foo)`)
- [ ] New homepage
- [ ] Complete docs https://github.com/imba/imba.io/issues/163

What else do we need to add? Are any of these wrong?

**Comment by eulores** [comment]
- [ ] Document imba command line options
- [ ] Expand SSR topic

**Comment by andregoldstein** [comment]
- [ ] Easy-to-access REPL

(Playground/scrimba)

**Comment by ericvida** [comment]
- [ ] Blank pages on iOS 10.3.3-12~ and some android devices as well that I've seen.

I know we can't support every browser, but where I am, fewer people have the latest devices than in more developed countries, so I'll take as much browser support as I can get.
