### ISSUE TITLE
Bug: imba create might fail for paths with spaces on them

### ISSUE THREAD

**Issue by mpeg** [imba/imba#525]
https://github.com/imba/imba/blob/e04d93e95bcb46d600a845d1eab535f8e18559f1/bin/imba-create.imba#L105

{dir} should be surrounded by quotes instead, simple fix but I'm not sure if it will work in every shell

Luckily, `git clone` will fail if you pass it extra arguments like this, otherwise the code a couple lines later: `rm -rf {np.resolve(dir,'.git')}` would run and potentially delete the wrong directory :)

I can submit a pull request for this one, but it might be worth to look into other places cli.exec might be called and ensure parameters are properly quoted – I could do it this weekend, plus test on windows

OS: MacOS
Shell: zsh

**Comment by Pistus** [comment]
Fixed in https://github.com/imba/imba/commit/cd4f4eb6176d73d54330437bfdbd5982935c8195 and then updated to double quotes in https://github.com/imba/imba/commit/2cafbec043ab7fd222e8a937c7585fe969fd1a31.
