### ISSUE TITLE
Avoid using `-ad` in class name 

### ISSUE THREAD

**Issue by Pistus** [imba/imba#531]
Reported by `vinesh` on [discord](https://discord.com/channels/682180555286380545/806112312570150944/829835934089740292).

An element on the page was blocked by a ad blocker because it had a class name ending in `-ad`. Can imba without much complexity re-generate the id or avoid generating class names with `-ad`?

**Comment by andregoldstein** [comment]
I wonder if it's only when ending directly with `-ad`. If so may be easier to add a suffix to all generated classnames rather than checking for `-ad` when generating

**Comment by Bohooslav** [comment]
I also have this issue.
