### ISSUE TITLE
Upgrade to Imba 2.0.0-alpha.132, hangs when compiling

### ISSUE THREAD

**Issue by braunse** [imba/imba#532]
### Details

After `npm outdated` showed me that a new release was available, I upgraded the compiler, but now compilation hangs with 100% CPU usage.

### Expected Behavior

Dev server runs as before

### Actual Behavior

Dev server consumes 100% CPU and does nothing

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Windows 10, node.js 8.1): WSL 2 running on Windows 10 x64
- Operating System and version (Mac or Linux): Linux Debian, node.js 14.16.0 from Nix packages (using node from Debian does not change the outcome)
- Useful link to screenshot or any other information:

### Steps to Reproduce

```bash
npx imba create repro # Uses 2.0.0-alpha.129 on my machine
# Accept all defaults
cd repro
npm run start
# dev server runs fine
npm i imba@2.0.0-alpha.132
npm run start
# Shows lots of compile ... messages, then hangs, consuming 100% CPU
# Have to interrupt with Ctrl+C
npm i imba@2.0.0-alpha.129
npm run start
# dev server runs fine again
```

</details>

**Comment by ericvida** [comment]
Having the Same issue

**Comment by Kabie** [comment]
https://github.com/imba/imba/blob/34a603e2b1ece10a5ac6563399a82565aaffa3b4/src/bundler/bundle.imba#L818-L819

Here the `body[end]` could be undefined, leads to a dead loop.

Not sure what change caused this though.
