### ISSUE TITLE
Imba 2 not rendering on 2017-2020 mobile browsers

### ISSUE THREAD

**Issue by ericvida** [imba/imba#537]
### Details
Imba 2 apps render as blank pages on devices that are not very new. 
For example this 
Android 8.1.0 Vivo Y91 Phone (released 2019)
- Chrome 79.0.3945.136 (Jan 29, 2020)
- Android 8.1.0 (Dec 5, 2017); vivo 1811 Build/OPM1.171019.026

iOS 10.3.3 iPhone SE (14G60) (July 19, 2017)
- Chrome 71.0.3578.89 (Dec 12, 2018)
- Safari 10.3.3 (js enabled, 2017?)

I don't have other iPhones older than 2020.

### Expected Behavior
Rendering of this app at https://khmer.tirado.app
![image](https://user-images.githubusercontent.com/13579055/116966495-83dbcc00-acda-11eb-8127-7deafb8803e3.png)

### Actual Behavior
Blank page at https://khmer.tirado.app

### More Android Phone details
![CleanShot 2021-05-04 at 13 08 15](https://user-images.githubusercontent.com/13579055/116966888-56435280-acdb-11eb-9d25-eec9ec4a18aa.png)
![CleanShot 2021-05-04 at 13 06 29](https://user-images.githubusercontent.com/13579055/116966919-652a0500-acdb-11eb-8ff1-81fa338e6833.png)

**Comment by ericvida** [comment]
> S
I see that I am using replaceAll in the khmer.tirado.app.
I have made other apps, and have the same issues I believe: 
- http://cham.tirado.app 
- https://islam.tirado.app

Maybe I am using unsupported JS in those as well. Take a look at those, if you will. If it's the same issue, now I know.

**Comment by Bohooslav** [comment]
My friend tried to babelize output of imba, and it works on his iOS 11. I hope esbuild. We have a simple app where we tried to use only supported technologies, but it doesn't work on mentioned above devices without babel.

**Comment by ericvida** [comment]
@somebee I see that I called an unsuported method, but I don't think that's the issue.
Here is a barebones site that doesn't work either. With nothing but an h2.
https://imba-2-alpha-133.netlify.app/

Of all issues, this one is the most pressing for me.

**Comment by Bohooslav** [comment]
Imba is using optional chaining operators in built js files which is not widely supported. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining. Probably this maybe the issue.

**Comment by Bohooslav** [comment]
@somebee It is working on iOS12

**Comment by Bohooslav** [comment]
My friend tested it on iOS 11, and it is working. On iOS 10.3 it doesn't work, but probably there is no big need to support it. I think this issue may be closed after testing on some android devices.
