### ISSUE TITLE
Animated svg asset causes infinite recursion

### ISSUE THREAD

**Issue by Pistus** [imba/imba#543]
Have tried to add this svg to the assets build pipeline on scrimba (using alpha.99) but it creates an infinite recursion error that I couldn´t spot in the svg. Tried removing different parts of the svg and it does not seem to be one element that causes it but rather the main chunk of images and groups with transforms. I will load it with a src instead, so this is not blocking me = let´s get back to it once we transition scrimba to imba2 stable.

**Comment by Pistus** [comment]
https://raw.githubusercontent.com/scrimba/scrimba-site/front-v3/assets/community.svg?token=AAN6YSDZFFA6X3MO6YMGKYTAWDMJE

**Comment by Pistus** [comment]
This asset does not create an infinite recursion but does also not load so maybe same cause.

https://scrimba.com/static/art/peep-crowd.svg

The server error log:
```
0|scrimba-site  | 2021-05-25T13:48:35: Error: Unable to load asset peep-crowd
0|scrimba-site  | 2021-05-25T13:48:35:     at ImbaContext.ext.create [as createAssetElement] (/Users/frode/scrimba/scrimba-site/node_modules/imba/src/imba/dom/asset.imba:27:9)
0|scrimba-site  | 2021-05-25T13:48:35:     at HomePageComponent.render (/Users/frode/scrimba/scrimba-site/src/pages/home.imba:84:20)
0|scrimba-site  | 2021-05-25T13:48:35:     at HomePageComponent.commit (/Users/frode/scrimba/scrimba-site/node_modules/imba/src/imba/dom/component.imba:111:23)
0|scrimba-site  | 2021-05-25T13:48:35:     at HomePageComponent.visit (/Users/frode/scrimba/scrimba-site/node_modules/imba/src/imba/dom/component.imba:103:15)
0|scrimba-site  | 2021-05-25T13:48:35:     at HomePageComponent.end$ (/Users/frode/scrimba/scrimba-site/node_modules/imba/src/imba/dom/component.imba:184:15)
0|scrimba-site  | 2021-05-25T13:48:35:     at render (/Users/frode/scrimba/scrimba-site/src/server.imba:135:6)
0|scrimba-site  | 2021-05-25T13:48:35:     at ServerResponse.res.render (/Users/frode/scrimba/scrimba-site/src/server.imba:480:13)
0|scrimba-site  | 2021-05-25T13:48:35:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by somebee** [comment]
I cannot access the animated svg you linked above - could you send it to me on slack or something?
