### ISSUE TITLE
Css 'not greater than' does not work with predefined screen sizes

### ISSUE THREAD

**Issue by Pistus** [imba/imba#544]
I want to hide some elements on screens smaller than 768px on scrimba.com (imba2 alpha.99)

This works: `d@!768:none`
This does not work: `d@!md:none`

Not a problem, just flagging if it should work for consistency.

**Comment by ericvida** [comment]
you could do `d@ltmd:none` (less than medium)

**Comment by Pistus** [comment]
Thanks, actually never use the `lt` / `gte` variants. But that looks better. I would say the `!` version should still be addressed.

**Comment by ericvida** [comment]
I agree. For consistency.
