### ISSUE TITLE
build command seems to put index.html in the wrong place

### ISSUE THREAD

**Issue by trafnar** [imba/imba#572]
### Imba Version: 155

running imba build produces this folder structure where index.html is outside of public, I think in previous versions it was inside public, and I placed the whole public folder on my server in order to deploy.

```
├── index.html
├── public
│   └── __assets__
│       ├── all-CT2DKRFQ.css
│       └── app
│           ├── client-FJHKUBIJ.css
│           ├── client-INHM49PI.js
│           └── client-INHM49PI.js.map
├── server.js
├── server.js.manifest
└── server.loader.js
```

**Comment by josedgm** [comment]
Yes. I'm having the same issue too.

**Comment by somebee** [comment]
Hope to have a fix tomorrow!
