### ISSUE TITLE
build cmd with no args outputs hmr script

### ISSUE THREAD

**Issue by nandoflorestan** [imba/imba#573]
### Imba Version: 2.0.0-alpha.155

When I run `npm run build` the output includes `<script src='/__hmr__.js'></script>`, but it shouldn't, since the built files must be compatible with any web server.

I also tried `npm run build --clean --mode=production` but this did not change the result.

**Comment by somebee** [comment]
The hmr.js script is injected in html assets at build time. This makes little sense - especially when you want to build a completely static site.

The most obvious solution is to just add an html comment/placeholder for the script, and when loading the asset on the server, in development mode, add the hmr there.
