### ISSUE TITLE
Emacs mode / support 

### ISSUE THREAD

**Issue by jasonm23** [imba/imba#58]
Anyone working on this?

**Comment by somebee** [comment]
Not that I know. If anyone is interested in creating one, I'd be more than happy to put up a bounty :)

**Comment by jasonm23** [comment]
Ok nice.

**Comment by jesuscript** [comment]
+1

**Comment by qwars** [comment]
+1

**Comment by qwars** [comment]
https://github.com/qwars/imba-mode.el

**Comment by scanf** [comment]
@qwars cool, could you open up a pull request adding it to the plugins section?

Thanks 🙏

**Comment by scanf** [comment]
It's been added.
