### ISSUE TITLE
css inside if statement causes tag not to render

### ISSUE THREAD

**Issue by trafnar** [imba/imba#602]
2.0.0-alpha.155

```
def render
    <self>
        if true
            css d:block
            <div> "Hello World"
```

This seems to cause the tag to not render at all with no errors, so it could be a confusing situation.

**Comment by somebee** [comment]
There are two ways to fix this. The easy one is to simply disallow it and throw an error from the compiler and tooling. The other approach will be more challenging; obviously the style need to be disabled when the condition is false. I'll need to think about how to implement it.

On another note; do you think it makes more sense that the css blocks applies to the immediately following tag? Currently they apply to their parent which sometimes feel awkward.

**Comment by trafnar** [comment]
Either of those solutions would be ok.

I think css inside the tag is ok, but I agree it's a hard decision. If it were on top, what would happen in this case?

```
css bgc:red
<div> "Hello" if condition?
<div> "World"
```
