### ISSUE TITLE
css selector aliases

### ISSUE THREAD

**Issue by ericvida** [imba/imba#603]
I think it makes sense in imba to have keyword aliases for selector symbols.

Here are some suggestion for what I mean.
`@child` for `>` 
`@all` for `*`
`@children` for `> *`
`@sibling` for `~`
`@pair` for `+`

Example of use:
```imba
css div
	@children@not-first
		ml:10px
	& @sibling p
		mt:10px
```
Thoughts?

Also, can selectors be supported in single line styles?
could these aliases help with that support?
example:
```
<div[margin-right@children@not-first:4rem]>
	# or
	css margin-right@children@not-first: 4rem

```

**Comment by somebee** [comment]
Instead of:
```
<div>
	css margin-right@children@not-first: 4rem
```
One could today write:
```
<div>
	css > mr@not-first: 4rem
```
Isn't that just as good? I guess the idea is that we cannot use these selectors in inline styles?
