### ISSUE TITLE
Cannot pass slot to child tag

### ISSUE THREAD

**Issue by haikyuu** [imba/imba#607]
Cannot pass `slot` to child tag.

```
tag root
	def render
		<self>
			<child>
				<slot>
				

tag child
	def render
		<self>
			<slot>
```
Rendering `<root>  "content"` throws an error: 
```
root.imba:6 Uncaught (in promise) TypeError: Cannot read property '__' of undefined
```

Is this expected? How can I make it work?

**Comment by somebee** [comment]
Interesting. I will see if the refactored dom stuff fixes this (I know it fixes a bunch of other issues with lists and conditionals). If not, I'm pretty sure it should be easy enough to support.
