### ISSUE TITLE
`if` property on elements

### ISSUE THREAD

**Issue by somebee** [imba/imba#615]
This one might seem a bit weird so just posting it here for discussion. Now that we have added support for transitioning elements in/out it finally makes sense to toggle elements using conditionals:
```imba
<self>
    if some-condition
        <Sidebar data=...>
            <some-content>
```
Previously I would do something like:
```imba
<self>
    <Sidebar data=... enabled=some-condition>
        <some-content>
```
and then add an `enabled` setter on `Sidebar` that takes care of stopping the element from rendering if not enabled etc. The biggest drawback of this was that `<some-content>` will always be reconciled whether or not `some-condition` is true.

While the new approach works, it adds a lot of indentation. Would it be helpful with a special `if` property on elements?
```imba
<self>
    <Sidebar data=... if=some-condition>
        <some-content>
```
Besides less indentation and code, another benefit is that we _could_ then allow reconciling properties etc on the tag that are placed before the `if=` property, and everything after the if, including children and content are skipped if the condition is false.

**Comment by andregoldstein** [comment]
I can't see a downside to having it as an option! You're right, indentation can sometimes be a consideration in Imba components. One are where I quite liked using ternary in React, to help keep the code terse

**Comment by haikyuu** [comment]
If we support if as an attribute, will we ever support `else` or `elif`?

I find it very powerful to be able to use the language freely even inside the DOM.
```
if cond
  console.log cond
  <div>
```
As opposed to all other UI libraries, it works and it's super powerful. I think adding support for `if` attribute would be a step backward for readability:
```
<div[a long list of styles go here] and a a lot of attributes @click=doSomething if=enabled>
```
This will be very hard to read and actually understand this won't show unless `enabled` is true. It could be a bit hard to debug.

That said, I'm not particularly against it. I just think indentation is a feature (that makes code readable) in this case. Plus, an `if condition` is much more powerful.

Thinking about it, why not add support for [directives like angular's](https://angular.io/guide/attribute-directives) ? This way, we could add support for if in user land.

**Comment by andregoldstein** [comment]
I think @haikyuu has a point. Although I guess if it was optional it could be left as a matter of taste.

@somebee Have you ever considered allowing support for `&&` or ternaries inside UI code (I'm assuming here it would probably be complex to implement?)

```
<self>
  <div>
    showNav && <Navigation>
    loading ? <Loading> : <Results>
    <main>
      ...
```

**Comment by somebee** [comment]
@andregoldstein To be honest I thought ternaries worked. If not, it definitely should. And so should the other I guess. If the `showNav && ` pattern worked I would myself have less need for `if=`.

**Comment by andregoldstein** [comment]
@somebee I think they'd be a great addition! Pretty sure they don't work at the moment..

**Comment by andregoldstein** [comment]
https://scrimba.com/scrim/czvkQBhr

```
tag App
	active = false
	<self>
		active && <p> "Active!" # Syntax error
		active ? <p> "Active" : "Not active" # Syntax error
		<p> active ? "Active" : "Not active" # Works
```

Syntax: Unexpected identifier

**Comment by somebee** [comment]
Most of these cases should be fixed in the next alpha :)

**Comment by andregoldstein** [comment]
Ternary fix and logical operators now possible in `alpha.171`.

See 52b24eec3bb38cfdd10a3290b6fb72caa4168f52 && e416433d50f3730f422c1287e025a9d66d5c9554

**Comment by shishtpal** [comment]
@somebee Is this issue has been resolved?
What is the new syntax?

**Comment by haikyuu** [comment]
@shishtpal here you go https://scrimba.com/scrim/c4Zvb4UR
