### ISSUE TITLE
stray words in css should produce an error

### ISSUE THREAD

**Issue by trafnar** [imba/imba#616]
### Imba Version: 2.0.0-alpha.170

If you include a stray word by accident in your CSS like I did below, it causes the css to not work at all, but there is no error.

```imba
<div> 
    css bgc:red foo
```

**Comment by somebee** [comment]
Is it just that the background-color doesnt work or does it break all styles / css as well? If only the former, it isn't that easy to deal with this. Css properties theoretically support an arbitrary number space separated values. I guess we could add much better diagnostics to highlight when a keyword like color has more values than the 1 expected value.

**Comment by trafnar** [comment]
hm yeah you're right, this only breaks the background color, which is kinda expected behavior, not sure if there was more to this when I logged it but I'll close it :)
