### ISSUE TITLE
Loops returning arrays of strings does not work

### ISSUE THREAD

**Issue by somebee** [imba/imba#62]
``` imba
tag example
    def render
         <self> for name in names
             "Name is {name}"
```

Does not work on subsequent renders. The dom reconciler was never made to support changing arrays of plain strings, but we either need to throw a warning, or make it work with strings as well. The latter should be easy enough, where we just opt out of the advanced comparator / reconciler when we encounter strings.

**Comment by erlingur** [comment]
I just hit this bug yesterday. Was wondering what the hell was going on :) It would be really awesome if this could be made to work properly.

**Comment by ismail-codar** [comment]
Following way is working.
```ruby
tag example
	def renderNames names
		for name in names
			"Name is {name} "
	def render
		<self>
			renderNames ['Name1', 'Name2']
<example>
```

**Comment by scanf** [comment]
Is this still an issue, three years later?

**Comment by somebee** [comment]
It was fixed a long time ago, but now it is an issue again in imba 2 😂
