### ISSUE TITLE
Template string not working properly

### ISSUE THREAD

**Issue by joserochadocarmo** [imba/imba#620]
### Details
I'm trying to put a Graphql query, but I think because the queries have braces '{', imba isn't compiling the code, I had to escape \\{ to work!

The braces is the problem, look at in VScode, and the error is clearer.
```javascript
const operationsDoc = `
	mutation upsert_user($name: String!, $email: String!) {
	insert_User(objects: [{name: $name, email: $email, is_active: true}], on_conflict: {constraint: User_pkey, update_columns: [updated_at]}) {
		returning {
			id
			email
			name
			updated_at
		}
	}
}	
`
```
Imagem
[https://ibb.co/TYBYkV8](https://ibb.co/TYBYkV8)

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Windows 10, node.js 8.1):
- Operating System and version (Mac or Linux):
- Useful link to screenshot or any other information:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by somebee** [comment]
This was implemented in `2.0.0-alpha.205` :)
