### ISSUE TITLE
Support "single fire" for hotkey modifier

### ISSUE THREAD

**Issue by trafnar** [imba/imba#637]
[from discord](https://discord.com/channels/682180555286380545/878109040750764042/903367826386079854)

It would be handy if there was a way to ensure hotkeys would only fire once per keypress, right now if I say @hotkey('esc') and then I hold down esc, it will fire repeatedly.

Mousetrap seems to support an argument for specifying if the event should fire on keydown or keyup, which would be nice to expose, and would help in this scenario (keyup will only fire once, despite how long I hold the key down) but I'd like to fire on keydown only once.

**Comment by somebee** [comment]
I think this was fixed by making single-fire the default behaviour and adding the [.repeat](https://imba.io/docs/events/modifiers/HotkeyEvent.repeat) modifier.
