### ISSUE TITLE
content within Global tag stopped working

### ISSUE THREAD

**Issue by trafnar** [imba/imba#643]
### Details
The following tag which uses `<global>` with content inside doesn't work, nothing is displayed in the browser

```
tag app
	<self>
		<global>
			<div> "hi"

imba.mount <app>
```

### Expected Behavior

The content within `<global>` should appear on the page

### Actual Behavior

Nothing appears

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Windows 10, node.js 8.1):
- Operating System and version (Mac or Linux):
- Useful link to screenshot or any other information:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by somebee** [comment]
Identified the issue. Will publish new alpha with fix today.
