### ISSUE TITLE
Support array syntax for `@hotkey`

### ISSUE THREAD

**Issue by andregoldstein** [imba/imba#646]
Mousetrap allows you to use an array of strings to enable multiple sequences triggering an event.

eg `<button @click=doThing @hotkey=["ctrl+s", "ctrl+l"]> "Click"`

From the docs:

```
Mousetrap.bind(['ctrl+s', 'command+s'], function(e) {
    _saveDraft();
});
```

I don't _think_ this works currently with the `@hotkey` modifier

**Comment by tuboythers** [comment]
@andregoldstein  There is an implementation of multiple key combos, but it is implemented like so:

```<div @hotkey('command+k|ctrl+k') @click=(console.log 'eventFired')>```

Splitting with a vertical pipe instead of actually supplying an array. Perhaps Imba should also support array as @hotkey arguments?

**Comment by Hotkey** [comment]
Hello @tuboythers This is Hotkey 💯
