### ISSUE TITLE
@touch.hold waits for additional input before firing

### ISSUE THREAD

**Issue by familyfriendlymikey** [imba/imba#664]
### Expected Behavior
@touch.hold should fire the callback once the duration has passed.

### Actual Behavior
@touch.hold only fires once the user either releases or moves the cursor after the duration has passed.

### Example
In the following example, the box shadow on the `.selected` class indicates that the box has been selected.
Currently, instead of waiting for the visual indication of the box shadow to show up, users have to guess when the
duration is over and let go of or move their pointer.
```
tag app
	selected = no
	def render
		css .box
			w:50px h:50px bg:blue3 rd:10px m:10px
			transition: background 200ms
		css .holding @important, .selected @important
			bg:red4
		css .selected
			bxs:2px 2px 10px -2px #000
		<self
			@touch.flag("holding").hold(duration=200ms)=(selected = yes)
			@click=(selected = no)
			.box
			.selected=selected
		>
imba.mount <app>
```

**Comment by somebee** [comment]
I definitely agree that the current behaviour is wrong. I've implemented a fix now, but there is one challenge with it. The way @touch works is that it will fire multiple times, so hold is a modifier that essentially stops the modifier chain until pointer has been held for a certain duration. Once you have held for that amount of time - all subsequent pointermove and pointerup events will be passed through.

One solution could be to have the hold modifier actually emit a separate `@hold` event once the 200ms has passed. Another alternative would be to actually let the initial pointerdown event through once held for 200ms, but still let subsequent pointermove and pointerup events pass as well. In this case, that would trigger (selected = yes) multiple times. This isn't a big problem, and at least better than the current behaviour I think.

**Comment by familyfriendlymikey** [comment]
Just tested alpha 209 and it appears to work well, thank you very much! I'm happy I don't have to use some hacky workaround for this now.

I see what you're saying. Unless this is what you already meant, we could also consider removing the `.hold` modifier and instead introduce a separate `@hold` event. Or perhaps have both work independently. I think it would help to know what the most common use case for this is.
