### ISSUE TITLE
Issue when using custom components

### ISSUE THREAD

**Issue by lorefnon** [imba/imba#680]
### Details

I am trying to convert an old vue app to imba. My app uses third party custom elements. Imba is throwing errors for these (non-imba) components. I am curious if this is not a supported use-case. 

### Expected Behavior

Ideally third party custom elements will work as they would if used in plain html.

### Actual Behavior

Imba fails with a runtime error complaining that a `__` slot is not available.

### Possible Fix

Maybe provide a way to indicate to compiler that a tag is not an imba component if it is non-trivial to support out of the box ? 

### Your Environment

Latest Ubuntu (Jammy), Node 18

### Steps to Reproduce

In the app generated by npx imba create (base template): 
```
npm install @shoelace-style/shoelace
```
Update client.imba to be
```
import "@shoelace-style/shoelace"

tag app
	<self>
		<header>
			<svg[w:200px h:auto] src='./logo.svg'>
			<p> "Edit {<code> "app/client.imba"} and save to reload"
			<sl-button> "Learn Imba"

imba.mount <app>
```

### Stack Trace

```
Uncaught TypeError: can't access property "__", this.__slots is undefined
    #getSlot fragment.imba:241
    createComponent core.web.imba:483
    render client.imba:12
    commit component.imba:140
    visit component.imba:132
    #afterVisit component.imba:223
    <anonymous> client.imba:14
```

The existence of a `__` slot seems to be an imba specific assumption. I can work around it by doing something like: 

    <sl-button innerHTML="Learn Imba">

which works. However this becomes unweidly for more complex composition of components. 

Thanks for creating this toolchain - the language looks really appealing. I am trying it for the first time so I may have made some basic mistake at my end. Thanks for your help in advance.

**Comment by lorefnon** [comment]
Thank you. I think primarily we need a way to bypass imba's custom slot system and be able to use native custom element slots (which doesn't seem possible atm)

**Comment by AngelMunoz** [comment]
I just hit this as well with ionic framework but it seems related to imba's slot management because some web components that are not using slots seem to work just fine

as an example


```html
<ion-button> "count" # this one works

<ion-button>
  <ion-icon slot="start" name="star"> # this one fails
  "Left Icon"
```
```
Uncaught TypeError: Cannot read properties of undefined (reading 'bottom')
    at [#getSlot] (imba.mjs:1:26959)
    at AppComponent.render (main.imba:40:12)
    at AppComponent.commit (imba.mjs:1:32481)
    at AppComponent.visit (imba.mjs:1:32410)
    at [#afterVisit] (imba.mjs:1:33498)
    at main.imba:65:16
[#getSlot] @ imba.mjs:1
render @ main.imba:40
commit @ imba.mjs:1
visit @ imba.mjs:1
[#afterVisit] @ imba.mjs:1
(anonymous) @ main.imba:65
```

**Comment by haikyuu** [comment]
Same with Swiper element https://swiperjs.com/element

**Comment by haikyuu** [comment]
@AngelMunoz @lorefnon I tested with both your examples and with swiper.js and it works now. Feel free to reopen an issue if something isn't working
