### ISSUE TITLE
route.params isn't recognized as valid

### ISSUE THREAD

**Issue by trafnar** [imba/imba#694]
There seems to be a type issue with `route` accessing `route.params` works, but shows an error in vscode.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/6732/182934553-dac7079c-f156-4a28-bf69-5f859a3e14de.png">

the documentation shows this as a valid use case here: https://imba.io/docs/routing

**Comment by somebee** [comment]
Typings for router has a long way to go, but this particular thing should be fixed in the latest alpha :)
