### ISSUE TITLE
route.params.foo is reported as an error

### ISSUE THREAD

**Issue by trafnar** [imba/imba#697]
according to the [router docs](https://imba.io/docs/routing) you can do something like:

```imba
<self> "Genre with id {route.params.id}"
```

it works, but is reported as an error in vscode tooling:
<img width="518" alt="image" src="https://user-images.githubusercontent.com/6732/184986042-c030a3d1-a5f2-4979-b07f-b589e7ffe440.png">

**Comment by somebee** [comment]
Has this been resolved in latest tooling?

**Comment by trafnar** [comment]
seems good in latest 👍
