### ISSUE TITLE
SSR rendering doesn't detect props?

### ISSUE THREAD

**Issue by haikyuu** [imba/imba#708]
Here is a reproduction of the issue: https://stackblitz.com/edit/node-cm1tap?file=main.imba

```
export default tag App
	count = 0
	def render
		console.log count
		<self>
			<button[c:green] @click.log("st")=(count++)> "Hello {count} times"

```

in the server, the render method is called correctly but the count doesn't appear in the rendered HTML. Instead it's rendered as `Hello  times`

**Comment by somebee** [comment]
It works if the count is `1` instead, so it has to do with 0 being "nullish" in js. Should be easy enough to fix
