### ISSUE TITLE
getting trouble to create imba app

### ISSUE THREAD

**Issue by JavedHussain-06** [imba/imba#740]
### Description

C:\Users\javed>npx imba create
√ Choose your template · electron-template
√ Name your project · jn
√ Configure package.json? (y/N) · true
√ Fill out the fields in package.json · 67% completed
√ Create project in directory: C:\Users\javed\jn? (Y/n) · true
i Generating files from template
'git' is not recognized as an internal or external command,
operable program or batch file.
✖ Something went wrong during creation
  Please report at https://github.com/imba/imba/issues

### Reproduction

https://imba.io/docs/intro#getting-started

### System Environment

```text
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 1.46 GB / 7.84 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.22000.120
```

**Comment by familyfriendlymikey** [comment]
This is fixed, thanks :)
