### ISSUE TITLE
Is there any method to get children of <slot>?

### ISSUE THREAD

**Issue by selegiline** [imba/imba#743]
something might like: 
```js
tag a-space < div
	class-prefix = 'card-space'
	
	<self.{class-prefix}-horizontol.{class-prefix}-align-center>
		for slot-item in <slot>
			<.{class-prefix}-item> <(slot-item)>
<a-space>
	<span> 'name'
	<button> '❤'
	<img> 
	...
        ...

**Comment by haikyuu** [comment]
You can already do this using `__slots.__` (__ stands for default slot) and you can access named slots as well

https://scrimba.com/scrim/cE4pMKs2

I'm just discovering this too 😆 This might be relevant for #752

**Comment by selegiline** [comment]
thanks, 😘，it's a fabulous framework and language. always bring me surprise
