### ISSUE TITLE
imba.serve throws a TypeError when using fastify@4.x

### ISSUE THREAD

**Issue by donaldp** [imba/imba#763]
### Description

`imba.serve` doesn't seem to work with newer versions of fastify.

I'm running `fastify@4.9.2` and its throwing: `TypeError: Cannot read properties of undefined (reading '_events')`.

However, when running `fastify@3.29.0` it works as expected.

### Reproduction

https://stackblitz.com/edit/node-4ju7gf?file=server.imba

### System Environment

```text
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 55.94 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/code/node_modules/.bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 105.0.3
    Safari: 16.1
  npmPackages:
    imba: ^2.0.0-alpha.225 => 2.0.0-alpha.225 
  npmGlobalPackages:
    imba: 2.0.0-alpha.225
```

**Comment by blokku-chan** [comment]
Here's the correct implementation:
`import Fastify from 'fastify'

const fastify = Fastify!

fastify.get '/', do 'Hello World'

imba.serve fastify.server

fastify.listen { port: 3000 }, do(err, address) console.log address`

You pass in the server instance which has the event handlers Imba is looking for, then separately start listening so Imba can intercept and do its magic

**Comment by donaldp** [comment]
Hey @blokku-chan 

Thank you, that worked 👍
