### ISSUE TITLE
[vscode] Suggestions/completions not working

### ISSUE THREAD

**Issue by jaymakes11** [imba/imba#777]
### Description

_Aside: Originally created this [here](https://github.com/imba/vscode-imba/issues/129) but then realized that repo seems to have been effectively replaced by the nested package in this repo ([here](https://github.com/imba/imba/tree/master/packages/vscode-imba)). This took a good bit of digging... might make sense to archive that repo?_

---

I'm a newbie to imba, evaluating it for a project. Would _really_ benefit from having editor suggestions and completions working.

Here's what I'm seeing in the plugin's output:

```
[{"suggest":{"preferAbbreviatedStyleProperties":"always"},"debugPort":0,"workspaceSymbols":{"scope":"imbaOnly"},"useImbaFromProject":true,"verbose":true,"checkImba":true}]
sending configuration
[{"suggest":{"preferAbbreviatedStyleProperties":"always"},"debugPort":0,"workspaceSymbols":{"scope":"imbaOnly"},"useImbaFromProject":true,"verbose":true,"checkImba":true}]
sending configuration
[{"suggest":{"preferAbbreviatedStyleProperties":"always"},"debugPort":0,"workspaceSymbols":{"scope":"imbaOnly"},"useImbaFromProject":true,"verbose":true,"checkImba":true}]
provideCompletionItems!! [object Object] undefined 1094 [path-to-file-redacted].imba {"triggerKind":0}
[{"line":32,"character":4}]
```

Pretty much the only thing I'm seeing working from the plugin are the popovers/insight-displays that show when hovering the mouse over certain keywords (e.g. hovering over `@touch` shows the relevant event handling documentation).

And just to make sure, suggestions and completions should be working, yes?

Grateful for any troubleshooting tips.

### System Environment

```text
System:
  OS: macOS 13.0.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 2.60 GB / 64.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
  npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
Browsers:
  Brave Browser: 108.1.46.144
  Chrome: 108.0.5359.124
  Firefox: 106.0.5
  Firefox Developer Edition: 108.0
  Safari: 16.1
npmPackages:
  imba: ^2.0.0-alpha.225 => 2.0.0-alpha.225
```

**Comment by jaymakes11** [comment]
Following advice found [here](https://github.com/imba/imba/issues/669), I've tried disabling all extensions except for this one and reloading and I'm still not seeing any suggestions/completions. Suggestions/completions are working with other languages.

**Comment by footurist** [comment]
@jaymakes11 Have you found a solution or workaround? I was revisiting imba and to my disappointment I discovered this aswell. Tried all sorts of things like combinations of old vscode version, nightly ts plugins, imba plugins, imba versions and so on.

What's especially perplexing is that even when combining versions of all the constituents from where I remember imba working flawlessly ( several months ago ) still nothing changes. It's pretty puzzling really.

**Comment by jaymakes11** [comment]
@footurist I learned on Discord that the vscode plugin has been broken for a while. Would have saved me (and it sounds like you, as well) a lot of time if this had been documented somewhere. Thankfully it sounds like a fix should be released soon. See https://canary.discord.com/channels/682180555286380545/682180555286380726/1060062191962824795.

**Comment by jaymakes11** [comment]
My issue turned out to be not having imba installed globally (`npm i --global imba`). Seems this is a requirement.
