### ISSUE TITLE
Intellisense isn't working.

### ISSUE THREAD

**Issue by peter-wasilko** [imba/imba#829]
### Description

Intellisense for 2.0.0-alpha.229 isn't working with the VSCode plugin v3.4.8 in Visual Studio Code - Insiders

Version: 1.77.0-insider
Commit: 215351a4cf2bada6f5be0857e716e5386a21cb1b
Date: 2023-03-15T05:38:06.980Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

### Reproduction

Syntax highlighting works, but hovering over imba symbols doesn't provide any hints, imba typing hints are ignored and everything types as 'any'. CSS intellisense doesn't work either, so there is no color picker or documentation offered.

### System Environment

macOS Monterey v. 12.6.3

**Comment by leoossa** [comment]
+1 👍 
I think it has to do with the extension itself. I changed auto-detected Imba language to TypeScript (for testing purpose) and it seems that if you change language the IntelliSense works. (Of course it doesn't make sense to use TypeScript IntelliSense for Imba, but I just wanted to check what is the cause of the problem)

Imba just stucks like this:
![image](https://user-images.githubusercontent.com/44456954/225613508-d416e4f9-72c0-4d66-bfde-d8556e6f86d4.png)

**Comment by vishwa-raj** [comment]
Having the same issue on Windows

**Comment by familyfriendlymikey** [comment]
Can you guys try locking your ts version to 4.9?

```
npm install -g typescript@4.9
```

In `settings.json` paste:

Mac:
```json
{
    "typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib/"
}
```

Windows:
```json
{
    "typescript.tsdk": "c:\\Users\\{User Name}\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib"
}
```

Linux:
```json
{
    "typescript.tsdk": "/usr/lib/node_modules/typescript/lib/"
}
```

**Comment by vishwa-raj** [comment]
@familyfriendlymikey Yes, it's working now.

**Comment by rraammiinn** [comment]
> Can you guys try locking your ts version to 4.9?
> 
> ```
> npm install -g typescript@4.9
> ```
> 
> In `settings.json` paste:
> 
> Mac:
> 
> ```json
> {
>     "typescript.tsdk": "/usr/local/lib/node_modules/typescript/lib/"
> }
> ```
> 
> Windows:
> 
> ```json
> {
>     "typescript.tsdk": "c:\\Users\\{User Name}\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib"
> }
> ```
> 
> Linux:
> 
> ```json
> {
>     "typescript.tsdk": "/usr/lib/node_modules/typescript/lib/"
> }
> ```

it didn't work for me .

**Comment by webNeat** [comment]
I was having this same issue and locking the TS version to 4.9 fixed it.

@rraammiinn you can try using the command `npm root -g` to get the path to your global `node_modules` directory (maybe it's not on the default path)

**Comment by CMiller3** [comment]
I've added my typescript4.9 path to VSCode, but I believe since I am using nvm, there are still some inconsistencies I am unable to track down. My settings looks as follows: 

```
{ ... 
    "typescript.tsdk": "/Users/charlie/.nvm/versions/node/v18.3.0/lib/node_modules/typescript/lib/",
... }
```

Anyone know the particulars of how the extension looks for typescript, imba, and others? I have a feeling the global imba package residing in .nvm also creates issues?

**Comment by kino-pi** [comment]
Have you tried installing the JavaScript/TypeScript nightly plugin? It'll give you an option to use a previous version, choose the last one for v4.9. That worked for me.

**Comment by CMiller3** [comment]
Goodness me. I had a screwed up VS Code, to fully delete my instance, removing all:

```
~/.vscode
~/Library/Application Support/Code 
/Applications/Visual Studio Code
```

Then reinstall VSCode and extensions, and then I could go through the proper steps of selecting a typescript instance. Oof.
