### ISSUE TITLE
Duplicate elements with same reference warning when elements in separate condition branches

### ISSUE THREAD

**Issue by illogikal** [imba/imba#836]
### Description

▲ [WARNING] [plugin imba] Duplicate elements with same reference

```
<self>
	if condition 
			<svg$icon>
	else
			<svg$icon>

```

**Comment by haikyuu** [comment]
I don't think this is a bug. These are indeed duplicates at compile time.

You can use ids and getElementById as a workaround for this use case. Alright?

**Comment by haikyuu** [comment]
The challenge with being in an if statement is that the ref actually changes. So it's not one ref, it's actually two. As there will actually be two references even if only one element is visible.
Consider this scrim https://scrimba.com/scrim/cDgPJZHv

**Comment by haikyuu** [comment]
I'll close this issue. Feel free to repoen if you feel it's not resolved
