### ISSUE TITLE
Imba command line -H --no-hashing has disappeared?

### ISSUE THREAD

**Issue by ubikitty** [imba/imba#846]
### Description

I need to embed an Imba file into a Django template. I tried many things but the only command line that seems to work is :  `imba build --web`

The problem is that it adds a hash after the file name so I tried the --no-hashing option ([found here](https://github.com/search?q=repo%3Aimba%2Fimba+no-hashing&type=commits) but it seems that it doesn't exists anymore. Was it replaced by another command/option? 

Because for now that would mean that I need to replace the filename in my django template each time I make a change to my Imba file... which is not really practical.

Maybe I am not using the correct command (I am new to this) but I assure you that I have tried many before posting...

### Reproduction

imba build --web --no-hashing

### System Environment

```text
System:
    OS: macOS 11.7.8
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
    Memory: 304.57 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 20.3.1 - ~/.nvm/versions/node/v20.3.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v20.3.1/bin/npm
  Browsers:
    Safari: 16.5.1
  npmPackages:
    imba: ^2.0.0-alpha.229 => 2.0.0-alpha.229
  npmGlobalPackages:
    imba: 2.0.0-alpha.229
```

**Comment by Bohooslav** [comment]
Yes it disappeared when there was some shift, probably to Vite, if I remember it well. I remember Sindre said that it should be easy to add, and I think that it should be definitely add back again.

**Comment by familyfriendlymikey** [comment]
If you're fine building your project with Vite, you can disable hashing in the `vite.config.js` file. Happy to provide more instructions if this is a viable solution for you.

**Comment by ubikitty** [comment]
@Bohooslav Yes it would be nice to have it back, I totally agree! =)

@familyfriendlymikey I am not using vite but why not if it solves my little hashing problem. Your instructions would be more than welcomed, thank you! My project is very simple since it just needs to compile Imba files to a unique set of javascript/css files ready to be embedded in a browser.

**Comment by ubikitty** [comment]
Finally I tried something like this (vite.config.js) which seems to work ok for now.
I am not sure of the options we may pass to the imba plugin.
If it is obviously completely wrong, do not hesitate to re-orient me in a sane direction!
Thanks

`export default defineConfig({`
`    base: '',`
`	plugins: [imba()],`
`	build: {`
`		outDir: 'static/imba',`
`		lib: {`
`			entry: 'src/app.imba',`
`			formats: ['es'],`
`			fileName: 'app',`
`		}`
`	}`
`});`

**Comment by Bohooslav** [comment]
@ubikitty, a little markdown hint use triple ``` around your code to opend multiline code block like this one
```
export default defineConfig({
    base: '',
	plugins: [imba()],
	build: {
		outDir: 'static/imba',
		lib: {
			entry: 'src/app.imba',
			formats: ['es'],
			fileName: 'app',
		}
	}
});
```

**Comment by familyfriendlymikey** [comment]
That looks about right to me. Glad you got it working :)

**Comment by Bohooslav** [comment]
@familyfriendlymikey if that is so easy, how much time it would take to add back the documented!!! `--no-hashing` feature?

**Comment by familyfriendlymikey** [comment]
Okay I've added it to undocumented https://imba.io/undocumented.

Also for posterity, this use case is documented https://imba.io/guides/incremental and provided as the module template https://github.com/imba/imba/tree/master/packages/imba/templates/module.

**Comment by Bohooslav** [comment]
Thank you! 💟
