### ISSUE TITLE
npx imba create fails (Windows)

### ISSUE THREAD

**Issue by AlectronikForge** [imba/imba#849]
### Description

I get asked for the project name or current dir,  when I enter a directory name it bails out with "Quit" in red, or if I use the current (empty, no git in hierarchy) one then the error "Creating a project in the current directory requires a clean git status" appears. In either case, no files are created.

On Linux it works as intended.

### System Environment

```text
npx: installed 1 in 1.783s

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 5.81 GB / 15.89 GB
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.67)
```

**Comment by familyfriendlymikey** [comment]
You need to update node to 16 or higher. I thought I put a warning in there but I guess it hasn't been released as part of a new version yet.
