### ISSUE TITLE
.imba require extension doesn't work

### ISSUE THREAD

**Issue by Aldlevine** [imba/imba#87]
I'm not sure if I'm missing something here; i've only recently started playing with Imba. However when I use the register.js module and attempt to require a .imba file directly in nodejs, I end up getting a `content.replace is not a function` error. I did a little investigation and it looks like this particular situation is solved by updating the require extension function to:

``` javascript
require.extensions['.imba'] = function (mod,filename){
    var content = imba.compile(fs.readFileSync(filename,'utf8'),{filename: filename});
    return mod._compile(content.js, filename);
};
```

(note that mod._compile is called on content.js rather than content).

Would this change affect any other functionality? If not, I'd gladly write a pull request for this.

**Comment by scanf** [comment]
Eyeballing the register.js file this seems to have been resolved, thanks!
