### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Namek** [imba/imba#88]
Every language and framework these days needs a logo. It's crucial to promotion.

**Comment by somebee** [comment]
I agree. Do you know of any good designers who might like to take on the challenge? :)

**Comment by Namek** [comment]
I would already pick one to do this if I knew. But I believe it's important to describe meaning/roots of the name or the general idea, maybe that will be inspiration for anyone seeing this topic.

**Comment by knaos** [comment]
Is Imba coming from gaming term - Imbalanced? :)

**Comment by somebee** [comment]
Yes :) In that spirit, i kinda like our current logo, even though it should be brushed up by a pro!

**Comment by scanf** [comment]
Logo was updated in f22459b2e1f7 (Updated logo on Readme, 2019-01-08).
