### ISSUE TITLE
Support InertiaJS

### ISSUE THREAD

**Issue by eznix86** [imba/imba#903]
Just copy pasted from the website, because it straight forward:

Inertia allows you to create fully client-side rendered, single-page apps, without the complexity that comes with modern SPAs. It does this by leveraging existing server-side patterns that you already love.

Inertia has no client-side routing, nor does it require an API. Simply build controllers and page views like you've always done! Inertia works great with any backend framework [...].

Inertia in action: https://demo.inertiajs.com/login

Documentation: https://v2.inertiajs.com/

**Comment by haikyuu** [comment]
There is an inertia adapter I created a long time ago but isn't maintained now. https://github.com/haikyuu/imba-inertia-adapter
Feel free to fork it and adapt to the v2 of inertia or send a PR.

But this is out of the scope of the programming language itself so I will close the issue.
