### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by judofyr** [imba/imba#97]
At the moment we're focusing on the following:

- **Smaller standard library:** Imba has changed a lot over the years
  and currently includes helpers and methods which should no longer be
  used. We'd like to cut down the standard library so that it contains
  the minimal code needed to write idiomatic Imba applications.

- **Compiler cleanup:** The compiler has a lot of cruft which needs to be cleaned up.

- **More like ES.Next:** Imba was created back when JavaScript was still
  ES3 and created its own syntax for many concepts. Now that JavaScript
  has evolved, it would be preferrable if we align the syntax closer to
  what the rest of the JavaScript community is used to. This includes
  import/export, async/await, destructuring assignment, spread and classes.

- **Compile to ES.Next:** Imba currently targets ES3 and we're paying a
  price for it with compiler complexity. As more and more
  browsers and environments support ES6 natively it's cleaner to target
  ES6 directly. If you need ES3 compatibility you can always use a
  transpiler (Babel, Bublé).

**Comment by scanf** [comment]
I am closing this since it's clearly not been kept up to date. We have better avenues for communicating the roadmap now. 

Thanks.
